### ISSUE TITLE
Searching a word under cursor breaks when this word is prepended with 'at' character

### ISSUE THREAD

**Issue by Valve** [atom/vim-mode#1000]
**Test file:**

```
world
def world
  @world
end
```

**Steps to reproduce:**
1. place a cursor on the first character (line 1, char 1, character `w`).
2. press `*` to trigger  _Search under cursor_ 
3. cursor jumps to `2:5` (correct)
4. press `*` to go to the next occurrence
5. cursor jumps to `3:4` (correct)
6. press `*` to go the the first occurrence again (i.e. loop), with intent to go to `1:1` cursor position.
7. cursor jumps to `3:3` - `@` char (incorrect)

Pressing `*` after cursor has jumped to 3:3 produces no results, cursor is stuck on `3:3`.

**Expected behavior:**

on step `7`, the cursor must jump to `1:1`, essentially starting a new cycle. Holding `*` pressed should loop over occurrences of `world` indefinitely.

**Software versions**
- Atom 1.6.2
- Vim mode 0.65
- Ex mode 0.8
- OSX El Capitan

**Links:**
http://vim.wikia.com/wiki/Search_and_replace_the_word_under_the_cursor

**Comment by Valve** [comment]
Wow, I've just opened the 1000th issue. Am I entitles to a free copy of Atom-Vim plugin?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
