### ISSUE TITLE
Wrong position when using '$' to move cursor in visual mode

### ISSUE THREAD

**Issue by ZhiruiLi** [atom/vim-mode#1002]
In visual mode, when pressing key '$', it should select all chars from the begin position of visual to the last char of the line, however, the editor now select the whole line not the last char.

This problem might cause by: [general-motions.coffee](https://github.com/atom/vim-mode/blob/a2464a8c434dfbe6db9b2ca99f6a49c50a4d8d31/lib/motions/general-motions.coffee#L382)

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
