### ISSUE TITLE
ciw on last letter should only select word

### ISSUE THREAD

**Issue by phzbox** [atom/vim-mode#1003]
Hi,

In normal vim:

foo("hello world");

If the cursor is on 'd' and I type ciw, it removes 'world", such that the line becomes: foo("hello ^"); where ^ is the new cursor in insert mode.

In atom, it removes 'world");' such that the line becomes '  foo("hello '

Is it normal behavior? Is it an easy fix? Maybe someone can point me in the right direction.

Thanks

**Comment by sandman21dan** [comment]
I've git this same issue, and didn't have it originally.

Using Windows 10.

**Comment by codelogicws** [comment]
This issue has been driving me nuts lol.

**Comment by codelogicws** [comment]
Using Linux Mint

**Comment by codelogicws** [comment]
This has been fixed in my environment over night. So unless this is an intermittent problem I'm guessing its been fixed.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
