### ISSUE TITLE
Option for disabling yyp to clipboard

### ISSUE THREAD

**Issue by smaili** [atom/vim-mode#1004]
Can we have an option for disabling/enabling the `yyp` (duplicate line) command to not overwrite the clipboard?  I'm not sure which version it was decided to become default behavior, but for those of us who are used to duplicating lines without affecting the clipboard, it'd be nice to have it as an option.

Running vim-mode 0.65.0 on Atom 1.6.2.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
