### ISSUE TITLE
Linewise visual block does not allow you to modify cursor position

### ISSUE THREAD

**Issue by billyvg** [atom/vim-mode#1005]
When you activate linewise visual block (`V`), you lose visual indication of your cursor position.

This may be related to not being able to move the cursor to end of line, and then move to matching bracket (`V$%`).

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
