### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by ghost** [atom/vim-mode#1007]
The first time I tryed the vim-mode the search didn't work (/{pattern}[/]).

I've tested with the lates version of atom inside Microsoft Windows 10.

**Comment by criztovyl** [comment]
Search also does not work for me.
Debian Testing
Atom 1.7.1
vim-mode 0.65.0

**Comment by scotte** [comment]
Maybe I'm just lucky, but seems to be working for me on Atom 1.7.2 with vim-mode 0.65.0.

**Comment by guiwp** [comment]
I've installed the [keyboard-localization](https://atom.io/packages/keyboard-localization) solved #1012 but the search feature I didn't get working.

Atom 1.7.2 with vim-mode 0.65.0 too.

**Comment by guiwp** [comment]
I solved the problem. My keyboard uses pt-BR layout, I had to update the file `%userprofile%\.atom\packages\keyboard-localization\lib\keymaps\pt_BR.json` with the following lines: `"193": {"unshifted": 47}`.

So simple...

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
