### ISSUE TITLE
Is there a .vimrc file somewhere I can configure?

### ISSUE THREAD

**Issue by grayskwrl149** [atom/vim-mode#1008]
Does vim-mode read a .vimrc or similar config file that I can tweak to my liking?

**Comment by jamesgecko** [comment]
Not right now; just the options available through this settings button.

![screen shot 2016-04-19 at 4 23 36 pm](https://cloud.githubusercontent.com/assets/44252/14654324/222bb35c-064b-11e6-96f6-d131cd60d6b8.png)

You can also specify mode-specific keybindings in `keymap.cson`. Mine looks like this:
```
'atom-text-editor.vim-mode:not(.insert-mode)':
  ';': 'ex-mode:open'
  ', t': 'fuzzy-finder:toggle-file-finder'
  ', s': 'pane:split-up'
  ', v': 'pane:split-left'
```

**Comment by AnilRedshift** [comment]
Or being able to ingest a .vimrc into the new world...

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
