### ISSUE TITLE
Can't input characters any more.

### ISSUE THREAD

**Issue by despairblue** [atom/vim-mode#1011]
see https://github.com/atom/atom/issues/11529

Seems to be a vim-mode issue, since deactivating all packages but vim-mode made it occur, whereas deactivating all packages it did not occur. Happens while changing from input to normal mode and then back to input. Happens sporadically, like twice per hour.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
