### ISSUE TITLE
The J command is slow

### ISSUE THREAD

**Issue by AaronM04** [atom/vim-mode#1014]
I selected a lot of JSON with visual mode, and then hit J, and it took about 3 seconds to put it all on one line. Let me know if I can help troubleshoot this more. Thanks!

**Comment by styx** [comment]
Not an expert, but it seems to be a general Atom issue of large files.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
