### ISSUE TITLE
Extending Vim Mode Operators

### ISSUE THREAD

**Issue by patrickw276** [atom/vim-mode#1015]
Is there any sort of API for extending the set of vim-mode operators? I've forked this repo to add an operator that emulates some of the functionality of [vim-commentary](https://github.com/tpope/vim-commentary) but it seems like this sort of feature would be better added via a standalone package that requires vim-mode. Any recommendations on how to implement this?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
