### ISSUE TITLE
W motion key not wrapping to next line

### ISSUE THREAD

**Issue by DrowsySaturn** [atom/vim-mode#1017]
I am using Windows 64 bit. Atom version 1.7.3. I am not able to wrap to the next line with the w motion key, but the e and b keys do work. I have noticed this only occurs when I am using CRLF line endings and not when I am using LF line endings.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
