### ISSUE TITLE
Backwards find motion should not include initial character

### ISSUE THREAD

**Issue by ngasull** [atom/vim-mode#1021]
`F` (Find) and `T` (Till) backwards motions do not behave like in vim when combined to operators. Indeed, the character at the initial position is included.

For example, if the cursor is on cake's `c` in

```
Can I lie to the freaking cake?
```

pressing `dFf` will produce

```
Can I lie to the ake?
```

The `c` of cake gets eaten, and it shouldn't :( we would expect instead

```
Can I lie to the cake?
```

I've already fixed the bug and I'll link a PR to this issue in a minute.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
