### ISSUE TITLE
% doesn't work for some ruby delimiters

### ISSUE THREAD

**Issue by calebmeyer** [atom/vim-mode#1024]
Ideally, the percent sign should jump to the matching symbol, even if that symbol is a word. In ruby, you use

``` ruby
def method_name

end
```

to define a method, and `do |param| param.foo end` to create a block.

The percent symbol should jump from def to end, and from do to end. Same for class..end, module..end, and possibly others I'm forgetting.

Note that it does still work for brackets `[]`, braces `{}`, and parentheses.

**Comment by brianpmaher** [comment]
I'd agree this issue is pretty annoying and is one of a few issues remaining with `vim-mode` that make it difficult for me to 100% switch from vim.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
