### ISSUE TITLE
'shift-d' delete with selection doesn't work as expected

### ISSUE THREAD

**Issue by eka** [atom/vim-mode#1025]
If I select a couple of lines and then I hit 'shift+d' I expect that will delete those lines completely but instead it behaves like normal 'd' in vim deleting till selection.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
