### ISSUE TITLE
Mapping keys

### ISSUE THREAD

**Issue by ayberkt** [atom/vim-mode#1027]
Is it possible to map keys with vim-mode as with vim? I have my navigation keys remapped for Colemak so it is impossible for me to use vim-mode unless I can remap keys in the same way.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
