### ISSUE TITLE
ywp works wrong

### ISSUE THREAD

**Issue by rashchedrin** [atom/vim-mode#1028]
Try this sequence of keys in vim and in atom's vim-mode:
`i1<enter><esc>kywp`
In vim I have 

```
11
```

in vim-mode

```
1
1
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
