### ISSUE TITLE
some Visual Commands not working

### ISSUE THREAD

**Issue by sunorry** [atom/vim-mode#1031]
eg: `vit`, it can not select inside the tag.

**Comment by tangledhelix** [comment]
It can select inside the tag in some cases, but it doesn't behave the same way Vim does. As far as I can tell, using this sample tag:

```
<span class="foo">Bar</span>
```

If the cursor is over `B` or `a`, then `vit` selects `Bar` as you would expect.

If the cursor is over `r` then nothing is selected.

If the cursor is over the `>` at the end of the tag opener, then it wrongly selects `>Bar`.

If the cursor is anywhere else, nothing is selected.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
