### ISSUE TITLE
Pressing tab after <Esc> implements two tabs

### ISSUE THREAD

**Issue by quoder** [atom/vim-mode#1032]
When I press "tab" after coming to insert mode by pressing "i" from normal mode, the editor adds two tabs instead which is weird. I have to backspace once to remove that extra tab. My tabspace size is 2.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
