### ISSUE TITLE
Show cursor in VISUAL mode.

### ISSUE THREAD

**Issue by trusktr** [atom/vim-mode#1033]
The cursor goes invisible while making a visual selection. it would be nice to keep showing the cursor.

**Comment by trusktr** [comment]
This would allow, for example, to type things like `%` to move the cursor to a matching brace (and thus modifies the VISUAL selection).

**Comment by trusktr** [comment]
Related: 
- https://github.com/atom/vim-mode/issues/1005
- https://github.com/atom/vim-mode/issues/936
- https://github.com/atom/vim-mode/issues/820

Interestingly, all those related issues have my exact same issue: needing to select whole blocks using `%` and similar.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
