### ISSUE TITLE
text-objects not the same as vim.

### ISSUE THREAD

**Issue by trusktr** [atom/vim-mode#1034]
typing `vi}` in Atom doesn't select exactly the same thing as in Vim.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
