### ISSUE TITLE
V line-select gets caught on word-wrapped lines.

### ISSUE THREAD

**Issue by zfjagann** [atom/vim-mode#1037]
If you use `V` (`shift-v`) to do a whole-line select, it gets caught when you use `j` or `k` to select past soft-wrapped lines.

For example, using the following text:

```
asdf
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum gravida nunc sem, nec ullamcorper mauris convallis nec. Ut ullamcorper urna quis metus maximus pretium. Phasellus convallis massa vitae ullamcorper mollis. Proin eu libero eu felis porttitor accumsan. Aliquam nec tellus lorem. Suspendisse quis magna ante. Integer in lobortis mi, lacinia elementum justo. Cras sed orci et nibh maximus bibendum et sit amet metus. Nullam non tortor quis ante suscipit varius.
blah
```

With soft-wrap enabled, if you hit `V` on the second line, you can't scroll up past that line. If you hit `V` on the third line, then go up past the second line, you can't go back down past the second line. Likewise if you hit `V` on line 1, then go down past the second line, you can't go back up to the first line.
If you disable soft-wrap the behavior goes back to normal.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
