### ISSUE TITLE
Obtaining vim-mode's word regex?

### ISSUE THREAD

**Issue by trusktr** [atom/vim-mode#1038]
Is there a way to obtain the regex that vim-mode uses when searching for words with `*` and `#`? For example, something I can put in my `init.coffee` after having installed vim-mode?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
