### ISSUE TITLE
Can't move to the last character of the line in insert mode

### ISSUE THREAD

**Issue by vivekn** [atom/vim-mode#1039]
Whenever I'm insert mode and editing a line, I can't move to the last character of the line. 
For example if I press `A` it takes the cursor to the second last character and there is no way to move the cursor to the last character in insert mode. The only work around is to ignore that the last character exists, make your edit, then goto normal mode and delete the last character. I think there is an off by one error somewhere.

**Comment by gregmacfarlane** [comment]
Exactly the same issue over here.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
