### ISSUE TITLE
Search doesn't work when the "/" character is made with [alt-gr + q]

### ISSUE THREAD

**Issue by hugollm** [atom/vim-mode#1040]
I previously owned a keyboard that didn't have a "/" character. So I had to make it with `[alt-gr + q]` (alt-gr is the alt key on the right of the space bar). It turned out to be much faster and I still use it today in other keyboards.

Despite the pressed keys, it generates the character "/" so it was suposed to bring up search mode (it works on vim).

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
