### ISSUE TITLE
python code folding

### ISSUE THREAD

**Issue by morenoh149** [atom/vim-mode#1041]
I see the language specific features is a discussion that is only in the beginning stages. https://github.com/atom/vim-mode/issues/807

I would like to get proper code-folding and comment (docstring) folding working in python code. This [stackoverflow answer](http://stackoverflow.com/a/7425005/630752) details the situation of code-folding python with vim.

Currently when I perform a code fold on the whole file (`z M`) the block comments aren't folded

``` python
"""
This is a big
python comment that
isn't folded with `z M`
"""
def foo():
    blah
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
