### ISSUE TITLE
Repeat till doesn't search past first match

### ISSUE THREAD

**Issue by strigonLeader** [atom/vim-mode#1044]
example line:

```
my example line
```

if the cursor is at the start of the line typing tl; will bring you to the first l, in vim it brings you to the second l

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
