### ISSUE TITLE
Proposal: Merge with ex-mode

### ISSUE THREAD

**Issue by AsaAyers** [atom/vim-mode#1047]
`ex-mode` [is looking for a new maintainer](https://github.com/lloeki/ex-mode/issues/116). There has been some confusion over `vim-mode` not including ex commands:
1. [Add handling for :w #520](https://github.com/atom/vim-mode/issues/520)
2. [is there any way to use ":" commands, eg, ":w" to write? #588](https://github.com/atom/vim-mode/issues/588)
3. [Problem with Command mode #554](https://github.com/atom/vim-mode/issues/554)

(just what I found in a couple minutes. I'm not sure if there are more)

With no one currently maintaining `ex-mode` this would be a good opportunity to just merge the two. Right now `ex-mode` is totally broken on atom 1.9, but there is no one [with access to merge the change](https://github.com/lloeki/ex-mode/pull/154#issuecomment-237099056)

**Comment by elitan** [comment]
+1

**Comment by iawia002** [comment]
+1

**Comment by sergiouve** [comment]
Is **_this_** package even alive?
#1045

**Comment by 50Wliu** [comment]
As mentioned in https://github.com/atom/vim-mode/issues/520#issuecomment-76037986, this isn't likely to happen.  But that might have changed now, I'm not sure.

**Comment by oddlyfunctional** [comment]
+1

**Comment by denqxotl** [comment]
+1

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
