### ISSUE TITLE
Function.extractParams is deprecated.

### ISSUE THREAD

**Issue by jazzpi** [atom/vim-mode#1050]
Occurs when marking a position with <kbd>m</kbd><kbd>a</kbd>:

Assigning custom properties to a marker when creating/copying it is
deprecated. Please, consider storing the custom properties you need in
some other object in your package, keyed by the marker's id property.

```
Function.extractParams (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:43:14)
MarkerLayer.markRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:192:71)
DisplayMarkerLayer.markBufferRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:74:62)
TextEditor.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor.js:1574:38)
VimState.setMark (/home/jasper/.atom/packages/vim-mode/lib/vim-state.coffee:918:30)
Mark.execute (/home/jasper/.atom/packages/vim-mode/lib/operators/general-operators.coffee:392:21)
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
