### ISSUE TITLE
'enter' and '+' do not work as expected with softwrap on

### ISSUE THREAD

**Issue by CodeCorrupt** [atom/vim-mode#1052]
With softwrap turned on, if a line is split across two or more lines on screen then the 'enter' and '+' keys can't move to the next line. 

This also causes issues with d + 'enter' where the expected behavior is to delete the line and the next. If executed on a split line then it only deletes that one entire split line (Even if it's split across more than two lines)

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
