### ISSUE TITLE
:x Closes entire atom editor

### ISSUE THREAD

**Issue by Altantur** [atom/vim-mode#1054]
Hi, when I giving command :x  atom editor instead of file. 
 I hope it is not feature :yum: .

**Comment by Altantur** [comment]
1+. I kind of used to close file such as conf. Please be not a feature.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
