### ISSUE TITLE
Spell Check Menu Not Compatable

### ISSUE THREAD

**Issue by CodeCorrupt** [atom/vim-mode#1055]
Spell check `ctrl-shift-;` does not work well with vim-mode
- To navigate the pop up using `up/down arrows` you must also first enter insert mode `i`.
- Pressing `esc` does not close the spell check menu, only exists insert mode in the spell check box.
  - After pressing `esc` in spell check you can edit the file underneath without spell check closing.

My proposal:
- Enable spell check menu navigation using `j`, `k` and `arrow keys` without being in insert mode.
- Still require insert mode to start typing in the spell check menu.
- If in insert mode in spell check menu, pressing `esc` should exit insert mode.
- If not in insert mode in spell check menu, pressing `esc` should exit spell check.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
