### ISSUE TITLE
Hitting single-quote twice doesn't move me

### ISSUE THREAD

**Issue by plbowers** [atom/vim-mode#1056]
I use double-single-quote often in command mode in vim to move me back to where I was before whatever I just did. So if I did a search then hitting '' should put me back where I was before I searched. If I go to a certain line # (123G) or to the bottom (G) to look at something and then hit '' it should put me back where I was. etc.

It appears that this double-single-quote is not implemented in vim-mode - it would be great if it could be implemented.

**Comment by plbowers** [comment]
OK, I've implemented this in my own development side of things. I need authorization to submit this on a new branch.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
