### ISSUE TITLE
Focus on empty pane breaks focus pane keymaps

### ISSUE THREAD

**Issue by dcalhoun** [atom/vim-mode#1057]
The vim-mode [focus pane keymaps](https://github.com/atom/vim-mode/blob/v0.65.1/keymaps/vim-mode.cson#L159-L174) _do not_ work if you are currently focused on an empty pane. I would imagine this has something to do with the scope of the keymap being specific to vim-mode (i.e. `'atom-text-editor.vim-mode:not(.insert-mode)'`).

---

### Behavior
1. Open a file in atom
2. Open a split pane <kbd>ctrl</kbd>-<kbd>w</kbd> <kbd>s</kbd>
3. Focus previous pane <kbd>ctrl</kbd>-<kbd>w</kbd> <kbd>p</kbd>

### Expected Outcome
Original file/pane is focused.

### Current Outcome
New empty pane remains focused.

---

The atom [focus pane keymaps](https://github.com/atom/atom/blob/v1.10.0/keymaps/darwin.cson#L92-L97) _do_ work while within an empty pane. Is it expected that vim-mode keymaps do not function in this context or is there a way to resolve this?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
