### ISSUE TITLE
Indentation by = doesn't work in java

### ISSUE THREAD

**Issue by kartagis** [atom/vim-mode#1058]
Hello,
I'm a beginner in java and sometimes I forget classes. I put them in when I remember, hence the need to re-indent. I go to the beginning of the file and indent with gg=G, but it just doesn't do it.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
