### ISSUE TITLE
move function by function via [[ or ]] or [}

### ISSUE THREAD

**Issue by plbowers** [atom/vim-mode#1064]
See "MOVING IN CODE BLOCKS" in http://vimdoc.sourceforge.net/htmldoc/usr_29.html#29.3

There are lots more options here, but moving a function up or down is the most helpful...

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
