### ISSUE TITLE
'r <enter>' should pay attention to indentation

### ISSUE THREAD

**Issue by fredemmott** [atom/vim-mode#1065]
Original content:

```
      foo(
        $bar, $baz)
```

If you move the cursor to the space after the comma then 'r<enter>' (replace space with newline), you get:

```
    foo(
      $bar,
$baz)
```

when it should be:

```
    foo(
      $bar,
      $baz)
```

If indentation is enabled, this matches vim, and also matches the rough equivalent `xi<enter><esc>`

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
