### ISSUE TITLE
repeat prefix and register prefix don't play nicely

### ISSUE THREAD

**Issue by plbowers** [atom/vim-mode#1066]
I want to copy 5 lines into the `a` register.

`"a5yy` doesn't work - it saves it into the default register and leaves `a` untouched

`5"ayy` works fine

I _believe_ that because the function `repeatPrefix` (in vim-state.coffee) saves the prefix into the operations stack and `registerPrefix` (in vim-state.coffee) does not that makes the repeat something that is remembered while the register gets forgotten if anything else (like a number) happens between setting the register and executing the command.

However, I will confess that this whole business of prefixes and opStack and etc (especially registerPrefix!) is a bit like "magic" to me right now. Is there any documentation of how this works anywhere?

I tried simply changing the definition of `registerPrefix` from this:

`registerPrefix: (e) ->
    new Prefixes.Register(@registerName(e))`

to this:

`registerPrefix: (e) ->
    @pushOperations(new Prefixes.Register(@registerName(e)))`

but that caused other problems immediately and I don't have even close to a deep enough understanding to be able to debug it from there.

Sorry - I tried.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
