### ISSUE TITLE
using asterisk key to search for keyword results in unexpected word append

### ISSUE THREAD

**Issue by Dowwie** [atom/vim-mode#1068]
I noticed that sometimes when I search for a keyword using the asterisk, atom will locate the keyword but also appends 'self' where the word is located (I'm coding using Python).

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
