### ISSUE TITLE
dw eats trailing whitespace

### ISSUE THREAD

**Issue by mikeduskis** [atom/vim-mode#1069]
Given the text

> spam spam spam
> spam spam spam

And the editor is in command mode 
And the cursor is at the start of the second "spam" on the first line

When the user types "2dw"

Then VIM 7.4.576 looks like this

> spam
> spam spam spam

But vim-mode 0.65.1 looks like this

> spam spam spam spam

**Comment by bronson** [comment]
This is fixed in vim-mode-plus.  It doesn't appear that anyone's currently trying to fix it in vim-mode, alas.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
