### ISSUE TITLE
Input Source should be disabled in command mode

### ISSUE THREAD

**Issue by Atry** [atom/vim-mode#1074]
All commands are broken in command mode if an Input Source is activated.

vim-mode should disable Input Source in command mode.

![screen shot 2016-10-24 at 18 21 45](https://cloud.githubusercontent.com/assets/601530/19642202/d3fb365c-9a16-11e6-9d6c-92e5f3dad8ae.png)

The snapshot shows the broken commands when I press `l` repeatedly if an Input Method is activated. The commands should have moved right the cursor if this bug is fixed.

**Comment by bronson** [comment]
Is this the workaround you need?

https://gist.github.com/rastasheep/bfc8266eeb58b899054c

If so, it's more a problem with Atom or Lion than vim-mode.

**Comment by Atry** [comment]
No.

This issue is related to https://github.com/atom/atom/issues/1092

**Comment by bronson** [comment]
Ah, gotcha.  I didn't know that you opened this issue on vim-mode-plus too: https://github.com/t9md/atom-vim-mode-plus/issues/446

Too bad the workarounds didn't work.  Hope the Atom team can get to this one day.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
