### ISSUE TITLE
Return in first character with ^ doesn't work

### ISSUE THREAD

**Issue by simepy** [atom/vim-mode#1080]
Hello,

Return in first character with ^ doesn't work.
my version of vim-mode: 0.65.1
my version of atom: 1.12.2

I try to uninstall vim-mode and disable other plugin in atom but no result.

Other person on the same bug ?

Thanks for advance

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
