### ISSUE TITLE
Implement "Auto Indent on Paste" option (aka ]p)

### ISSUE THREAD

**Issue by apazzolini** [atom/vim-mode#1084]
When pasting yanked text via p/P, vim-mode doesn't adjust the pasted text to the current indent. I've made a short GIF describing the behavior here: https://cl.ly/142c2x200k3m

In VIM, this behavior can be achieved by using `]p`. Specifically, that leverages the `]` mark (described [here](http://vimdoc.sourceforge.net/htmldoc/motion.html#`]))

Atom exposes this behavior behind the "Auto Indent on Paste" option in Editor settings. It would be incredible if vim-mode respected that flag (or alternatively simply implemented the motion and let users remap p themselves).

Thanks for considering!

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
