### ISSUE TITLE
Can i use keybinding without delay like in Sublime text

### ISSUE THREAD

**Issue by haacki47** [atom/vim-mode#1090]
**Hi.**
I used **vim-mode** in **sublime text**, that was awesome. And then when i came to **atom**, i want to effect like in sublime text.
Look this.
I use 'd f' keybinding for change to normal mode by vim

![subl-gif](https://cloud.githubusercontent.com/assets/14221550/25062640/8687b996-21d8-11e7-98aa-95ea92e52740.gif)

As you can see, when i press 'd' it displayed fast, without delay

_Look at Atom Vim-mode_
I use 'd f' keybinding for change to normal mode by vim

![atom-gif](https://cloud.githubusercontent.com/assets/14221550/25062669/209aef94-21d9-11e7-8b24-a6086aad4778.gif)

When i press 'd' in editor, it displayed with delay. Or when i press 'd' and then press other key it display fast.

How to i can use 'd f' keybinding but without delay in insert mode when i press just 'd'?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
