### ISSUE TITLE
Undo on autocomplete/snippet

### ISSUE THREAD

**Issue by TyberiusPrime** [atom/vim-mode#1091]
Activating a snippet or autocompletion does not place an undo point.

Reproduce:
in insert mode
"something snippetprefix[tab][escape][u]"
will remove everything you just inserted,
not only the last snippet.
Ditto for autocompletion.

This is unfortunate to my mind because I have some fairly verbose snippets that trigger unintentionally on occasion and  now I either retype my whole insert-mode sequence, or I fall out of my flow to decide what I need to remove from this snippet.

I think it's a vim mode issue - vanilla atom seems to do the right thing.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
