### ISSUE TITLE
Unable to use dt$ or ct$ in tex file

### ISSUE THREAD

**Issue by dionyziz** [atom/vim-mode#1097]
Steps to reproduce:

1. Create a new TeX file and save it as `test.tex`
2. Type the following single line in it:
```
a $test$
```
3. Move the cursor to the beginning of the line
4. Type dt$

Expected behavior: The part "a " is deleted.
Actual behavior: A "$" is inserted.

A similar error exists for ct$

I am using atom-latex.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
