### ISSUE TITLE
keyword completion with ctrl-n and ctrl-p in insert mode

### ISSUE THREAD

**Issue by zenhob** [atom/vim-mode#110]
In insert mode only, `ctrl-n` and `ctrl-p` attempt to complete the current word. `ctrl-n` searches forward and `ctrl-p` searches backward. In Vim the completion list is specified by the `complete` option which by default completes words from every open buffer as well as the tag list.

http://vimhelp.appspot.com/insert.txt.html#i_CTRL-N
http://vimhelp.appspot.com/insert.txt.html#i_CTRL-P

**Comment by ZuBB** [comment]
@zenhob your solution does not work for me. is it outdated?

**Comment by dm-wyncode** [comment]
@zenhob I tried as well and did not achieve the expected result.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
