### ISSUE TITLE
can't save file

### ISSUE THREAD

**Issue by abusizhishen** [atom/vim-mode#1100]
:w and :x can't save file content 
:1 will direct to other line,but first line

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
