### ISSUE TITLE
Atom selection with Vim keybindings

### ISSUE THREAD

**Issue by adiospace** [atom/vim-mode#148]
When I use Select Next (Cmd+D) or Select All (Ctrl+Cmd+G) and then some vim keybinding such as change word cw, to change all selected words (same happens with `x` or other vim keybindings) it changes the world + 1 char more.

![select-with-vim-bindings](https://f.cloud.github.com/assets/31248/2365575/15c80f2a-a6d0-11e3-9502-381c419d0d39.gif)

**Comment by agudulin** [comment]
Seems to be fixed now.

**Comment by bronson** [comment]
Agreed, I can't reproduce this.

**Comment by laughedelic** [comment]
I have the same bug when using Vim `s` action, it always deletes 1 more character.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
