### ISSUE TITLE
Search box doesn't hide with escape

### ISSUE THREAD

**Issue by milyord** [atom/vim-mode#165]
If using vim-mode and cmd-shift-f or cmd-f. After bringing the search box up and then focusing on the file the escape key does not hide the search box. It all works fine if vim-mode is disabled.

Also the block cursor in vim-mode disappeared after the last update. I'm not sure if you guys just removed that because you think the editor is cooler without it but definitely you should bring it back. The block cursor is awesome.

**Comment by bronson** [comment]
It does if focus is in the search box.  If you're hitting Esc and it's not going away, hit Cmd-F and then Esc.

**Comment by bradleyflood** [comment]
Is there any chance `esc` could function in this logic as suggested above?

1. `esc` from insert mode go to command mode
2. `esc` again (already in command mode now) -> Close search box etc. (fall back to default Atom functionality)

**Comment by JeremyChase** [comment]
I have an [open PR](https://github.com/atom/vim-mode/pull/869) that addresses this issue.

**Comment by stv8** [comment]
In the mean time here is a temp fix

```
'atom-text-editor.vim-mode.normal-mode':
  'escape': 'core:cancel'
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
