### ISSUE TITLE
Add support for `_` as an alternative to `^`

### ISSUE THREAD

**Issue by lloeki** [atom/vim-mode#168]
Useful for layouts where `^` is a dead key.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
