### ISSUE TITLE
Disable the special character popup when holding down `l`

### ISSUE THREAD

**Issue by danielmurphy** [atom/vim-mode#175]
When you hold `l` to motion right, OSX gives you an option to insert a special character. Has anyone figured out a solution for not showing that popup? I'd rather not disable that system wide.

![kprqcu](https://f.cloud.github.com/assets/798783/2423844/ee80d6b6-ab9f-11e3-8ec1-396f963da99d.gif)

**Comment by PandaWhisperer** [comment]
^^ This works.

**Comment by izuzak** [comment]
This issue has been open for quite a while, but there's actually an older issue on the core Atom repository asking for this as well: https://github.com/atom/atom/issues/1092 (also see https://github.com/atom/electron/issues/47 for more context). I'm going to close this issue in favor of that one since this isn't just about vim-mode and it's good to have one all the feedback in one place.

I'll also add a comment to that issue about the the approach mentioned by @rastasheep in https://github.com/atom/vim-mode/issues/175#issuecomment-48708542 which allows users to disable the popup just for Atom -- thanks for that! :zap:
