### ISSUE TITLE
cs: vim-surround

### ISSUE THREAD

**Issue by lloeki** [atom/vim-mode#188]
vim-surround is non standard but is an incredibly useful plugin by Tim Pope.

Example commands:

`cs"'`: change closest double quotes surrounding the cursor to single quotes
`csw{`: wrap word with spaced curly braces
`csW)`: wrap Word with non-spaced parentheses
`<selection>S[`: wrap selection in spaced square brackets
`cst{`: change surrounding html/xml tag with spaced `{`
`csw<foo>`: surround word with `<foo></foo>`
`csw<foo class='bar'>`: surround word with `<foo class='bar'></foo>`
`ysft)`: wrap current cursor position to next `f` character with non-spaced parentheses

The last ones may be a bit convoluted to implement, especially without real text-object support, but the first four are definitely among the most frequently used ones.

**Comment by tangledhelix** [comment]
AFAICT in the past couple of years, vim-surround has matured and is "done" - I use it all the time in fact. Can this issue be closed?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
