### ISSUE TITLE
Add support for recording and playback commands

### ISSUE THREAD

**Issue by pengux** [atom/vim-mode#192]
In VIM, record commands sequences with `q+[identifier]` and end recording with `q`. To playback the recorded commands, use `@+[identifier]`. It's also possible to use repeaters, like `5@[identifier]` to play the recorded commands 5 times.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
