### ISSUE TITLE
yank-line + visual mode(normal) problem

### ISSUE THREAD

**Issue by SKAhack** [atom/vim-mode#211]
I try below

```
# `^` is cursor
0^12
345
678
```

keydown: `vljY`    ( `j` is need for some other reason... )

I expected `"`register become `012\n345\n`, but result is `12\n34`.

**Comment by barrymoo** [comment]
+1, also will provide some visual aides to the bug. I was hoping I could figure out how to fix the code, but I am not sure where to start.

![cursor](https://cloud.githubusercontent.com/assets/3086255/10942382/e63d6732-82dd-11e5-8241-725e37acf911.jpg)

followed by `vggY`, move over pane, `P`

![paste](https://cloud.githubusercontent.com/assets/3086255/10942483/5b30d10a-82de-11e5-93f4-efb6140a97a4.jpg)

The `y` and `Y` behave exactly similar in vim-visual-characterwise-mode. It is not how vim behaves.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
