### ISSUE TITLE
'l' in vim mode opens web inspector

### ISSUE THREAD

**Issue by d2fn** [atom/vim-mode#217]
Doesn't happen on all files all the time, but seems to happen pretty consistently on this one [markdown file I'm editing](https://gist.githubusercontent.com/d2fn/22663b374a26a9609282/raw/29e9a09c9ff8d4bdc8dc832b70c9714e5381537d/gistfile1.txt). 

NB: I have soft wrap turned on and the markdown preview window open when this happens.

**Comment by izuzak** [comment]
Just tried reproducing this with various examples using soft wrap (including the file linked to in https://github.com/atom/vim-mode/issues/217#issue-32855351), and wasn't able to. I believe this was fixed in #406, so I'm closing the issue. If anyone can still reproduce in Atom 1.0.11 -- let me know and please provide an example.
