### ISSUE TITLE
Implement {}, [], and ()

### ISSUE THREAD

**Issue by hos** [atom/vim-mode#228]
{}, [], (), $ and others should be implemented. 
Here is a full list: http://vim.wikia.com/wiki/Moving_around

**Comment by bronson** [comment]
@hos, just curious, does it work now?

**Comment by hos** [comment]
{} and $ work, [] and () do not. I have atom 0.205.0 and vim-mode 0.53.0.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
