### ISSUE TITLE
Have command mode block cursor render behind the text

### ISSUE THREAD

**Issue by calebmeyer** [atom/vim-mode#241]
I stay in command mode a lot, and it's nice to be able to see where my cursor is at a glance and also be able to see what character lies under it. 
Sublime fixed this problem by making a solid cursor, and causing all the text it was on to become a contrasting color to the cursor. ![screen shot 2014-05-14 at 11 10 32 am](https://cloud.githubusercontent.com/assets/3342777/2973907/54b6cbb8-db82-11e3-842c-b8c810b2ec20.png)

However, atom's cursor gets painted over the text, which means if I use any opacity >0.5, I can't read the character under the cursor.
A simple solution to this is making the cursor render behind the character it is on. I'd do it myself, but I don't understand why setting the background-color (in the vim mode less file) paints in the foreground.
![screen shot 2014-05-14 at 11 05 53 am](https://cloud.githubusercontent.com/assets/3342777/2973859/ae92d9b6-db81-11e3-8e93-45bc171cd50b.png)

**Comment by max-sixty** [comment]
I think this now isn't possible given the change to tiling; is that correct?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
