### ISSUE TITLE
Marks do not move when buffer changes

### ISSUE THREAD

**Issue by tonatiuh** [atom/vim-mode#259]
Steps to reproduce:
1. In a file containing this text:

```
text in line 1
text in line 2
text in line 3
```
1. If a set a mark in "text in line 3" line
2. And then I modify the document in this way

```
text in line 1
text in line 2
text in line 2.1
text in line 3
```

then when I go to the mark I set it goes to "text in line 2.1" line instead of going to "text in line 3" as VIM does.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
