### ISSUE TITLE
Selecting text doesn't turn on visual mode

### ISSUE THREAD

**Issue by TakSuyu** [atom/vim-mode#295]
It's minor, because you can just press v, but a nice attention to detail.

**Comment by maxbrunsfeld** [comment]
Hey all, I know there was some controversy on this. I implemented it because I feel like it's worth trying out for a while. Now that multiple cursors work properly, this behavior makes vim-mode compose really nicely with the `Find and Replace: Select Next` command. I'm thinking that this will allow for nice interplay with other packages that select text too. Previously, selecting text in normal mode resulted in a strange experience in my opinion.
