### ISSUE TITLE
visual block mode inserting

### ISSUE THREAD

**Issue by lebster** [atom/vim-mode#299]
when doing the following command to inset text before multiple lines I am not getting the correct result. Instead my visual block selection is just overwriting the selection

ctrl-v - make selection
shift-i - type text  (at this point it over writes my selection )
esc - still left with just the overwritten text

I have checked to make sure ctrl-v and shift-i are mapped to vim mode already.

**Comment by ddelrio1986** [comment]
That is correct. I've noticed that there is no visual block mode yet.

**Comment by bronson** [comment]
#468, #516, and #645 have made the same observation.

There's been some effort to put block selection in Atom core.  When it happens, hopefully this issue will be closed: https://github.com/atom/atom/issues/2306

**Comment by ardrigh** [comment]
It would be good to have this feature supported to allow block commenting in the same way it works with Vim.

e.g.<kbd>Ctrl+v</kbd> select visual block <kbd>Shift+i</kbd> <kbd>#</kbd> <kbd>Esc</kbd>.

It's a feature I use a lot when editing code blocks.

**Comment by jacekkopecky** [comment]
@ardrigh you may benefit from multiple cursors here - see my last comment in #468 
Exactly for what you describe above, I can now do `cmd-down` a bunch of times to create as many cursors as I need, and then `i#<esc><esc>` - the second `<esc>` will get rid of the multiple cursors.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
