### ISSUE TITLE
Cursor gets 'stuck' in command mode with basic motion commands

### ISSUE THREAD

**Issue by cbeams** [atom/vim-mode#318]
Using:
 - Atom 0.103.0
 - Vim Mode 0.10.1

Repro:
 - Open a new file in Atom. Name it 'simple.md'
 - Paste the following text:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Sed sit amet ipsum mauris. Maecenas congue ligula ac quam viverra nec consectetur ante hendrerit. Donec et mollis dolor.
```
 - Size the editor window so that wrapping causes three lines of text to show up
 - Go to the beginning of the line
 - Press 'l' with the intention of moving the cursor character by character to the end of the line
 - Notice that the cursor gets 'stuck' just after the soft wrap
 - Go to the beginning of the line again
 - Press 'j' with the intention of moving down line by line to the last of the three wrapped lines
 - Notice again that the cursor gets 'stuck'.

Workaround:
 - None; go into insert mode and use arrow keys to get around.

Unfortunately, this problem is so distracting that it renders Vim Mode (and therefore Atom for my purposes) unusable. I'm quite keen on using Atom (particularly with Zen Mode) for Markdown editing, so I'll stay tuned to see if this issue gets worked out. Thanks!

**Comment by izuzak** [comment]
I just tried reproducing this with various examples using soft wrap (including the one from https://github.com/atom/vim-mode/issues/318#issue-35765767), and wasn't able to. I believe this was fixed in #406, so I'm closing the issue. If anyone can still reproduce in Atom 1.0.11 -- let me know and please provide an example. Thanks!
