### ISSUE TITLE
ctrl-d in visual mode doesn't highlight text as in vim

### ISSUE THREAD

**Issue by mode80** [atom/vim-mode#335]
In visual mode, ctrl-d to advance forward a half-page, doesn't highlight the text, as it does in "real vim".

**Comment by doublemarked** [comment]
I don't know the status of this, but it drives me crazy also. It makes it difficult to select blocks of text with the keyboard.

**Comment by bronson** [comment]
Looks like this is fixed?  Discussion is in #627

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
