### ISSUE TITLE
Motion commands not working with parentheses or brackets 

### ISSUE THREAD

**Issue by dlo** [atom/vim-mode#336]
Cursor position is represented by '_'. Next command is di + surrounding character.

```
"hello, _world"
'hello, _world'
(hello, _world)
[hello, _world]
{hello, _world}
<hello, _world>
```

Output:

```
"" # correct
'' # correct
(hello, world) # no change
[hello, world] # no change
{hello, # incorrect behavior
<hello, world> # no change
```

**Comment by wmayner** [comment]
:+1:

Selecting inside brackets, etc. still fails when the cursor is on either the closing bracket or the character immediately preceding it.

It looks like this is because of two things:

1. With this implementation, “inside” brackets is taken to mean that the cursor is between the brackets; in Vim, the cursor can be _on_ a bracket and you can still select whats inside.
2. Entering visual mode moves the cursor one position to the right, so that when you're on the character immediately to the left of the closing bracket and you press `v`, your cursor moves onto the bracket, which results in the above behavior.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
