### ISSUE TITLE
ge motion is not supported

### ISSUE THREAD

**Issue by openjck** [atom/vim-mode#337]
**Steps to reproduce:**
1. Create a new document
2. Add the following text to the first line: `one two three four five`
3. Move the cursor to be anywhere in the word `three`
4. Type `ge`

**Expected result:**
Cursor is moved to the letter `o` from the word `two`

**Actual result:**
Cursor is moved to the letter `r` from the word `four`

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
