### ISSUE TITLE
gT fails to execute when "Settings" tab is reached

### ISSUE THREAD

**Issue by ghost** [atom/vim-mode#340]
BUG: The tab commands gt and gT work fine, but are non responsive when "settings" is open as a tab. afaik this is not a problem caused by dvorak

**Comment by bronson** [comment]
Personally, I wouldn't expect the Vim keys to work in the settings dialog anyway.  If they did, then I would expect the Vim cursor, navigation, visual selection, etc to work too.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
