### ISSUE TITLE
æøå etc. as keybindings

### ISSUE THREAD

**Issue by noh4ck** [atom/vim-mode#359]
It is not possible to use Norwegian (or other non-ascii? characters) as keybindings.
On Norwegian keyboards, the index finger is on j (move left) and the little finger on ø (move right).

**Comment by bronson** [comment]
Might be similar to https://github.com/atom/vim-mode/issues/403

As mentioned there, if this binding doesn't open the about box, then it's probably worth filing an issue on the [atom keymap](https://github.com/atom/atom-keymap) repo.

```cson
'*':
  'ø': 'application:about'
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
