### ISSUE TITLE
Collapsing code causes issues with right-arrow navigation

### ISSUE THREAD

**Issue by Rosseyn** [atom/vim-mode#363]
Windows 8.0, Atom v0.115.0, occurs in safe mode

To replicate: open a file (confirmed in php and js files), collapse a relatively good sized code block and move cursor below the collapsed block; now attempt to use the right arrow to navigate to the end of various longer lines of code/text.

The cursor stops in seemingly arbitrary places, and not in the same column of each line. Some lines might not allow right arrow navigation at all, some might do it all the way to the default 80 char line guide, generally somewhere in between though.

Not seeing any errors in dev tools console.

[See here for video.](http://discuss.atom.io/t/collapsing-code-causes-issues-with-right-arrow-navigation/10932/3?u=rosseyn)

Also a link to issue in the Atom repo where we suspect it is vim mode related. 

https://github.com/atom/atom/issues/3026

**Comment by izuzak** [comment]
I just tried reproducing this with various examples using folds (including the example given in https://github.com/atom/vim-mode/issues/363#issuecomment-50573672), and wasn't able to. I believe this was fixed in #406, so I'm closing the issue. If anyone can still reproduce in Atom 1.0.11 -- let me know and please provide an example. Thanks!
