### ISSUE TITLE
Selection does not follow Ctrl-F and Ctrl-B in visual mode

### ISSUE THREAD

**Issue by jspahrsummers** [atom/vim-mode#376]
**Version:** Atom 0.120.0, vim-mode `v0.13.0-4-gfb6e37a`
**Steps:**
1. Enter visual mode with `v` or `V`.
2. Press `j` or `k` to select a line above or below and verify that selection works.
3. Press `^F` or `B`.

**Expected:**
The whole page forward or back is added to the selection.

**Actual:**
After scrolling, there's no more selection.

**Comment by dcalhoun** [comment]
Would love to see this as well as support for [CTRL-B](http://vimhelp.appspot.com/scroll.txt.html#CTRL-B) and [CTRL-D](http://vimhelp.appspot.com/scroll.txt.html#CTRL-D) as well.

**Comment by bronson** [comment]
This appears fixed.  It works on my 0.199.0: ctrl-f, ctrl-b, ctrl-d, and ctrl-u all appear to work the same way as vim.

**Comment by dcalhoun** [comment]
Works for me too.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
