### ISSUE TITLE
Camelcase movement operators

### ISSUE THREAD

**Issue by jspahrsummers** [atom/vim-mode#377]
Given the programming languages I typically work in, one of my favorite Vim plugins is [camelcasemotion](http://www.vim.org/scripts/script.php?script_id=1905). I'd love to build something similar for Atom, but it seems like it would depend on support within vim-mode directly.

Is there any precedent for implementing non-standard movements like this, or does anyone have recommended reading for building a separate package that relies upon vim-mode?

/cc @nathansobo @ymendel @bhuga @mcolyer

**Comment by dsandstrom** [comment]
I'll start adding support for this.  However, what should the keymaps be?  I was using `q`, which works great, but that would conflict with macros if they are ever added.  I would like to use a single key, but there are no keys available that I know about.

**Comment by deiwin** [comment]
The vim plugin seems to sacrifice the comma. I don't know if that's the best idea, though.

**Comment by deiwin** [comment]
The `\` and `|` characters seem to be available.

**Comment by jacekkopecky** [comment]
Just a thought - I could imagine a configuration option, or a per-language option somehow, for `w` and `b` to mind camelCase. Additionally, this setting could somehow affect the `iw` and `aw` text objects. 

It's about time (and this might be the place) that someone reinvents the principles of modal text editing in the modern setting of windows, panes, big screens, widespread camelCase, colours, highlights and so on.

**Comment by deiwin** [comment]
This would probably mean that support for `iW` and `aW` should also be added to differentiate between the 2 possible meanings of *a word*. But I would probably like the uppercase versions to behave as the current lowercase versions do, instead of making them work as they currently do in *vim* (using the WORD definition).

Or maybe just have different bindings for all 3 cases. I mean, we have more modifier keys available than just shift.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
