### ISSUE TITLE
cancel commands, when its not applicable

### ISSUE THREAD

**Issue by ryrun** [atom/vim-mode#378]
Create a tab with just on line. Type following: 3dd

On vim, it just beeps, because it cant delete 3 lines.
On atom, it removes the line.

Its important to avoid this minor problems, because it can cause trouble when the macro stuff is coming in future. Because vim stops macro playback, when a command cannot be applicable to the current line.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
