### ISSUE TITLE
Visual mode does not support * register

### ISSUE THREAD

**Issue by JoshCheek** [atom/vim-mode#396]
You can do `"*yy` to yank the current line to the clipboard, but cannot visually highlight a selection and then do `"*y` (seems to just copy it into whichever register is copied into by default).

**Comment by bronson** [comment]
This appears fixed.  versions 0.200.0 / 0.48.0.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
