### ISSUE TITLE
Auto save?

### ISSUE THREAD

**Issue by ernsheong** [atom/vim-mode#409]
I love would to have the option to auto save as soon as we go back to command mode, just like in XVim for XCode.

**Comment by bronson** [comment]
Saving on focus lost isn't good enough for your needs?  (see the autosave core package)

Just hoping to avoid adding another option.

**Comment by ernsheong** [comment]
Cool. That's helpful enough. Thanks!

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
