### ISSUE TITLE
Scroll window down command moves by 3 lines not 1

### ISSUE THREAD

**Issue by dcalhoun** [atom/vim-mode#430]
The [scroll window down command](http://vimhelp.appspot.com/scroll.txt.html#CTRL-E) moves the screen by 3 lines not 1. [Scroll window up](http://vimhelp.appspot.com/scroll.txt.html#CTRL-Y) works as expected.

**Comment by dcalhoun** [comment]
This appears to be fixed via atom/atom#5951.

**Comment by dcalhoun** [comment]
This bug is now back.

**Environment**
- Mac OS X 10.11.1 (15B42)
- Atom v1.1.0
- vim-mode v0.6.3

**Comment by dcalhoun** [comment]
@as-cii any thoughts as to why this bug returned?

**Comment by as-cii** [comment]
Interesting, does upgrading to the latest Atom version help somehow? We've recently changed that code path, so the new version might help fixing this. Also, could you tell if it happens consistently?

Thanks, @dcalhoun!

Anyhow, I should be able to take a look later this week. /cc: @maxbrunsfeld

**Comment by dcalhoun** [comment]
No, I'm running the latest Atom (1.3.1) currently and the bug still exists. Yes, this behavior has always been consistent. It was fixed briefly with atom/atom#5951, but came back in ~1.1.0 and happens consistently.

**Comment by maxbrunsfeld** [comment]
I'm not sure what exactly caused this to regress, but the scroll commands are currently fragile because they're trying to scroll to an exact screen row by calling `editor.scrollToScreenPosition`, which is more for *revealing* a given screen position, not specifying an exact scroll position. I'll update vim-mode to use the new `{get,set}FirstVisibleScreenRow` model APIs.

**Comment by maxbrunsfeld** [comment]
Thanks for catching this @dcalhoun. It should be fixed in vim-mode v0.64.
