### ISSUE TITLE
Switch case of text doesn't work right(g~, gU, gu ...)

### ISSUE THREAD

**Issue by learning** [atom/vim-mode#438]
Switch case of text doesn't work right as vim, including `g~{motion}`, `gU{motion}`, `gu{motion}` etc.

**Comment by jacekkopecky** [comment]
@learning is this still an issue now that #556 was merged?

**Comment by bronson** [comment]
This sure looks fixed to me.  Are there any more differences from Vim?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
