### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

### ISSUE THREAD

**Issue by benogle** [atom/vim-mode#470]
_From @jonatasdlp on December 9, 2014 20:35_

Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

**Atom Version**: 0.153.0
**System**: linux 3.17.4-1-ARCH
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package

_Copied from original issue: atom/atom#4480_

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
