### ISSUE TITLE
Way to use atom's find/replace with the keyboard.

### ISSUE THREAD

**Issue by Industrial** [atom/vim-mode#490]
Hello.

My search settings with Vim are `set hlsearch` (to highlight search matches) and `set incsearch` (to jump to the first match while searching). With atom with vim-mode, I can't see what other parts of my document match my search.

Is it possible to use the default atom find and replace panels for searching, totally controlled with the keyboard?

**Comment by maxbrunsfeld** [comment]
Almost all of the `Find and Replace` package's functionality is controllable via the keyboard. If you hover with your mouse over the buttons on the panel, it will show you the keyboard shortcuts. Do you mean that you would want vim-mode to add additional key-bindings for these actions to make them work like vim?

**Comment by Industrial** [comment]
Right now ctrl+f is next page in vim-mode, so the atom search is not
directly accessible with the keyboard. I'm also wondering if it's possible
to operate the atom search window with the keyboard entirely.

**Comment by maxbrunsfeld** [comment]
It is indeed possible to operate the search window with the keyboard entirely. I guess you'll need to add a new key mapping for `find-and-replace:show` command.

**Comment by alem0lars** [comment]
@maxbrunsfeld it would be great to reuse the existing find and replace (from the package) instead of a custom functionality.
For example typing `/` should open the same window of `Meta+F`.
In my opinion, simply adding the hotkeys to the existing find and replace functionality is a lot better.

**Comment by MrMattBusby** [comment]
While this issue can probably be closed (I ended up here frustrated by key bindings and wanting a hot-key to turn off/on `vim-mode` itself) +1 for @alem0lars suggestion. Hopefully `vim-mode` is kept super light and Atom'ic (and separate from `ex-mode`) and will more utilize `find-and-replace`, `fuzzy-finder`, etc.

**Comment by maxbrunsfeld** [comment]
I agree with these suggestions. To make Atom's find-and-replace interoperate with vim's operators and with its repeat system will take some work however. @jacekkopecky and @t9md have some ideas about this, I believe.

**Comment by t9md** [comment]
For me, I'm currently not using vim's search feature, and I also want to control with keyboard everything but atom's find-and-replace lack some of keyboard control feature, so I created following two package to complement that.
- [isearch](https://atom.io/packages/isearch) incremental search package. Support smart case and save search history to vim-mode's search history(this means repeat isearch's search with vim-mode's `n`, `N`.). I map `/` and `?` to this package.
- [project-find-navigation](https://atom.io/packages/project-find-navigation), this provide keyboard manipulation to result of project-find result of find-and-replace package, you can work around found rest with `j`, `k`(whichever keymap you configure).

For vim-mode's native search motion feature, I feel it need to be improve so that user don't have to search and try another tools. It should be natively good(But currently not so I use created, use different package).

**Comment by alem0lars** [comment]
Are there any updates on this issue?

**Comment by bentheax** [comment]
> Right now ctrl+f is next page in vim-mode

**Comment by RootlessAgrarian** [comment]
Sorry if this is a necropost, but I am just dipping my toe into Atom/Platformio because working with point/click editors (Arduino IDE for one) feels like typing with gloves on to this ancient hacker :-)   I am _almost_ 100 pct delighted by Atom with the vim-plus extension, but am cruelly disappointed that s/foo/bar/g is not supported.  

Googling reveals that this appears to be a contentious issue, so I don't like to fuel discord... but 40 years of muscle memory is painful to contravene.   I realise that (as mentioned above) it is possible to control Atom's find/replace dialog with keyboard presses and chords, but they are all modifier-heavy and (for me) a strain on the hands.

Has anyone got a plugin or patch or hack or *anything* that would provide :s/foo/bar/<scope> for vim-plus in Atom?  If not, I guess it's back to xterm and elaborate makefiles, etc. for me.  At a certain age it becomes hard for the leopard to change its spots :-)

**Comment by MewX** [comment]
Still wanting this feature :/

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
