### ISSUE TITLE
cmd-d should clear pending key combinations

### ISSUE THREAD

**Issue by brandonhorst** [atom/vim-mode#498]
```
c (going to type ciw)
(realize that I should actually need to change this word a few times)
cmd-d (select next occurrence of this word with a new cursor)
(does not enter Visual mode like normal)
c
(it triggers `cc` for each cursor)
```

Pressing `cmd-d` with stored keystrokes should clear them and enter visual mode like normal. I would expect pressing the second `c` to do a normal visual-mode change-in-word.

**Comment by bronson** [comment]
This is an interesting problem.  `ctrl-shift-w`, `ctrl-shift-b`, `ctrl-shift-f`, `alt-shift-b`, `alt-shift-f`, `ctrl-shift-e`, `ctrl-shift-a` are some of the other selection key combinations that should clear the stored keystrokes.

Also, `c` `alt-b` `c` fails.  It should move to the beginning of the word and resume changing.  Also `alt-f`, `cmd-right`, `cmd-left`, `cmd-up`, `cmd-down`, and just about any Atom navigation key.

also `c` `cmd-j` `c`, and all the sublime edit commands, like `ctrl-T`, `alt-backspace`, `alt-delete`, etc.

Maybe any non-vim-mode key needs to clear the stored keystrokes?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
