### ISSUE TITLE
Can't paste from register 0

### ISSUE THREAD

**Issue by phoenixeliot** [atom/vim-mode#501]
I'm finding that the key sequence "0p does not paste from register 0 as expected, and instead hitting 0 moves to the beginning of the line. Is the command binding for this missing?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
