### ISSUE TITLE
Add motion to go to next/previous bracket ( '[{' / ']}' )

### ISSUE THREAD

**Issue by nesmyslny** [atom/vim-mode#518]
I think, for anyone, who works with C style languages, this motion is really helpful.

Documentation: http://vimhelp.appspot.com/motion.txt.html#%5B%28

**Comment by TheStealthReporter** [comment]
Code: https://github.com/t9md/atom-vim-mode-plus/issues/315

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
