### ISSUE TITLE
Add support for 'gv' (start visual mode with previous selection)

### ISSUE THREAD

**Issue by nesmyslny** [atom/vim-mode#519]
`gv` reselects the area that was selected before. I often use it to select, yank, reselect and comment some code. This was also mentioned here https://github.com/atom/vim-mode/issues/246#issuecomment-69242369, but I think it's good to have a separate issue for that.

For more details: http://vimhelp.appspot.com/visual.txt.html#gv

**Comment by jacekkopecky** [comment]
related to #597 - when that's fixed, this should be easy to implement

**Comment by willthemoor** [comment]
I didn't realize how often I hit `gv` in vim until trying to switch to atom. Missing it! Wish I could be useful on #597. So, a lame +1 anyway.

**Comment by ramongilmoreno** [comment]
Yet another vi user aching for his trusted gv command.

**Comment by hobofan** [comment]
https://github.com/t9md/atom-vim-mode-plus has `gv` implemented, if that's a feature you can't live without.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
