### ISSUE TITLE
It would be nice to paste in my current vimrc

### ISSUE THREAD

**Issue by wamoyo** [atom/vim-mode#523]
I'm not experience enough to know the scope of I'm asking for, but I do know, as a vim user. If I could paste in my vimrc, I could switch to atom a lot more readily.

**Comment by maxbrunsfeld** [comment]
I don't think this package is ever going to interpret vimscript. Anyone else have any ideas on how to make it easier to switch from vim?

**Comment by wamoyo** [comment]
Hmm... that's interesting. I don't much like vimscript, I wonder if there's a web standard solutions (javascript, or json config file)

**Comment by gepoch** [comment]
My two cents :D

vim-mode is not a vim emulator. If people want to be able to use their vimscripts in a modern UI, there are some projects that are targeting this (such as [neovim](https://github.com/neovim/neovim)) vim-mode's scope is mostly around getting the user interface to use modal control targeting vim's operation method.

Rather than trying to rewrite vim in javascript (which has actually already been [done](https://github.com/coolwanglu/vim.js)) I think a better way forward is to bring our favorite things about vim into atom. [vim-mode] does a huge portion of the work, and enables a familiar vim workflow. Beyond that, the atom ecosystem provides more options.

[vim-surround](https://github.com/gepoch/vim-surround) (for example/shameless plug)  attempts to reproduce the functionality of the old vim-surround plugin, but in a way that integrates into the Atom environment nicely. Atom's vim-mode was extended using Atom's ideas for what makes a plugin.

I find coffeescript and the atom ecosystem to be a massive improvement over the various hacks that you need to get a working plugin in vim. Atom just brings the good parts forward :)

**Comment by maxbrunsfeld** [comment]
I agree, @gepoch. I think this kind of thing should be implemented in a separate package (if anywhere). It's now possible for other packages to interact with vim-mode through Atom's [services API](https://atom.io/docs/latest/creating-a-package#interacting-with-other-packages-via-services). See #540.
