### ISSUE TITLE
visual modes inconsistencies

### ISSUE THREAD

**Issue by lloeki** [atom/vim-mode#533]
`5ggvkk` produces this in vim and Atom on the same content:

![screenshot 2015-02-20 10 37 19](https://cloud.githubusercontent.com/assets/75445/6284050/9cbd6f1e-b8ec-11e4-8dfc-358e69bba84c.png)

![screenshot 2015-02-20 10 39 42](https://cloud.githubusercontent.com/assets/75445/6284082/ed0b824e-b8ec-11e4-8b52-303abc749fb2.png)

But it produces this in atom on another file:

![screenshot 2015-02-20 10 41 41](https://cloud.githubusercontent.com/assets/75445/6284107/2410227c-b8ed-11e4-81fb-5085f9f5ed83.png)

Also, in both cases, going back to command mode (ESC) is not consistent with vim, putting the cursor at the end of the previous line:

![screenshot 2015-02-20 10 43 13](https://cloud.githubusercontent.com/assets/75445/6284127/5024b738-b8ed-11e4-93cd-229d2528ade3.png)

![screenshot 2015-02-20 10 43 07](https://cloud.githubusercontent.com/assets/75445/6284131/556a57ac-b8ed-11e4-8c64-72916b29c4d7.png)

![screenshot 2015-02-20 10 43 03](https://cloud.githubusercontent.com/assets/75445/6284138/5add9d52-b8ed-11e4-9b3e-75aa1a02a437.png)

**Comment by bronson** [comment]
The behavior with Picture 3, where line 5 is blank, seems OK to me.  Have you tried Vim on the same file?  You might find Vim's behavior even worse.  :)  (it needlessly moves the cursor to the end of the line)

Your second observation is correct: vim-mode leaves the cursor in the wrong spot when hitting Esc.  (moves it to the end of the previous line instead of leaving it at the beginning of the current line)  That definitely feels like a bug and might merit its own issue.

**Comment by lloeki** [comment]
Well, this matters somehow as a seasoned vim user will expect `5ggvkkd` to delete lines 3, 4 and 5. However weird, the non-visual line behaviour movement is very vimesque and those gritty details that get ingrained in muscle memory trip me up regularly enough I thought it warranted a report.

By the way, on the sample below, doing `4gglvkk` in vim is internally consistent with the reported behavior, as it selects the character under the cursor. Atom's vim-mode behaves similarly to vim in that case, so it is not internally consistent (as above reported, it does not select the newline invisible character under the cursor).

```
foo
bar
baz
qux

top
pot
glob
not
```

Whatever, my "duty" (so to speak) is done, and the rest lies not in my hands :-)

**Comment by bronson** [comment]
Oh, I agree.  I'm just trying to finish up a patch that makes vim-mode behave like Vim with dj and dk.  Unfortunately, it requires special-cases depending on whether the cursor is on the first or last line, it requires more code to implement.  But, as you say, finger feel is important.

If you feel strongly about something in vim-mode, your duty might include writing a spec.  :)  It's not too hard once you get the hang of it, and that would greatly improve the chances of someone coming along later and implementing the functionality.

(i think...  i've only been using vim-mode for a few days so i could also be very wrong.)

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
