### ISSUE TITLE
Add ZZ command (save and close current file)

### ISSUE THREAD

**Issue by Germanika** [atom/vim-mode#535]
ZZ saves the open file before closing. Equivalent of :wq
This is a command I miss quite a bit  from Vim. Currently, I end up with a lot of open files because the  way of accomplishing this is ctrl+s, ctrl+w q which is rather tedious, so I end up leaving files open.

**Comment by dsandstrom** [comment]
This would be helpful.

**Comment by sQu1rr** [comment]
+1

Currently use following workaround
keymap.cson
```cson
'atom-text-editor.vim-mode:not(.insert-mode)':
    'Z Z': 'sq:saveAndClose'
'.tree-view':
    'Z Z': 'sq:treeToggle'
```

init.coffee
```coffeescript
atom.commands.add 'atom-text-editor', 'sq:saveAndClose', ->
    pack = atom.packages.loadedPackages['tree-view']
    treeView = pack.mainModule.treeView

    selected = treeView.selectedEntry()

    editor = atom.workspace.getActiveTextEditor()
    if editor.getPath()
        editor.save()

    atom.workspace.getActivePane().destroyActiveItem()

    if !atom.workspace.getActivePane().getActiveItem()
        treeView.selectEntry(selected)
        treeView.show()

atom.commands.add '.tree-view', 'sq:treeToggle', ->
    pack = atom.packages.loadedPackages['tree-view']
    treeView = pack.mainModule.treeView
    treeView.toggle()
```

**Comment by tangledhelix** [comment]
This can be closed, I think - `ZZ` works in the stock package now as far as I can tell.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
