### ISSUE TITLE
Undo doesn't group multiple character input

### ISSUE THREAD

**Issue by keyneston** [atom/vim-mode#55]
When entering insert mode and then typing multiple characters 'u' will undo everything since entering insert mode.

atom currently will undo each character individually.

_edit_: Clarified first sentence.

**Comment by jacekkopecky** [comment]
This seems resolved; could be closed? (just noticed)

**Comment by bronson** [comment]
Agreed, is there anything left to implement?

**Comment by janbaykara** [comment]
I've noticed that undo will often not group multiple changes by packages that are affected by a single command. Is this by design, or... ?

**Comment by jacekkopecky** [comment]
@janbaykara can you please give an example?

**Comment by janbaykara** [comment]
I remember https://atom.io/packages/autoclose-html + multiple cursors, then undoing, resulted in borks.

Also, https://atom.io/packages/atom-alignment cannot be undone - Undo simply ignores the fact that the plugin made changes.

**Comment by jacekkopecky** [comment]
I don't use either of these packages so I need a bit more - any chance you could write down some steps to reproduce the problematic behaviour, please?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
