### ISSUE TITLE
vim inserts are interrupted by cursor movement, vim-mode inserts aren't

### ISSUE THREAD

**Issue by jacekkopecky** [atom/vim-mode#565]
In vim, if you move your cursor around (with mouse or with arrow keys), an insert gets confirmed and a new gets started - they can be undone separately, and only the last part can be redone. To demonstrate: 
1. have `1234` in the text editor, with cursor on `2`
2. type `iab<right>cd<esc>` – you will have `1ab2cd34` in the text editor
3. typing `u` should only undo `cd`, typing `.` should only insert `cd` in the current place

But in vim-mode, typing `u` undoes both `ab` and `cd` insertion, and typing `.` inserts `abcd`. 

See [vim docs](http://vimhelp.appspot.com/insert.txt.html#ins-special-special) for more info about this.

I'll now have a quick look if I can fix this easily.

**Comment by peterjeliot** [comment]
I'd like to emphasize the importance of this one — sometimes I'm in insert mode for a long time, and find that undo undoes WAY too much. Sometimes the last several minutes of edits. I find that this leaves me no meaningful way to only undo a little of it.

It also overrides the behavior of cmd-z (which makes sense, but leaves no alternative when `u` undoes too much)

**Comment by MarkusSN** [comment]
+1

**Comment by jacekkopecky** [comment]
Thanks, I should soon get some time to rebase this to the newest state of
the code. @maxbrunsfeld any suggestions in case you don't quite like how it
was done?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
