### ISSUE TITLE
`i'`, `a'` and `i"`, `a"` text objects broken when string terminator is under the cursor

### ISSUE THREAD

**Issue by andyearnshaw** [atom/vim-mode#566]
This may be two separate bugs, but perhaps not.  For a quick demonstration, paste the following text into Atom:

```
'foo' + 'bar'
```

Place the cursor on the second `'` and press `va'` to see that `'bar'` is selected instead of `'foo'`.  Press `da'` to see that `' + '` is deleted instead of `'foo'`.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
