### ISSUE TITLE
vimState.history never seems to be emptied

### ISSUE THREAD

**Issue by jacekkopecky** [atom/vim-mode#569]
Hi, I'm not sure if this is intentional, but `vimState.history` seems to be growing with all the recordable operations ever done in a window, until the window is closed. Before #568, only `history[0]` was used; but #568 makes use of multiple recent entries, but still we should be able to clean up the history somehow.

Should we maybe keep only the last _some number_ of history entries?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
