### ISSUE TITLE
Does not repeat inserts

### ISSUE THREAD

**Issue by cptaffe** [atom/vim-mode#580]
Pressing `30i`, typing some characters, and then pressing `[esc]` should repeat that insert operation the expressed (in this case 30) number of times.

For example `3i#[esc]` should print `###`

Although other repeat operations work properly, this does not seem to work.

**Comment by scottmessinger** [comment]
I can confirm.

**Comment by jacekkopecky** [comment]
Indeed, #609 addresses this but needs a bit more work.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
