### ISSUE TITLE
Implement visual marks < and >

### ISSUE THREAD

**Issue by jazzpi** [atom/vim-mode#597]
In vim, when entering visual mode, the marks < and > are set to the beginning and end of the selection.

Implementing this feature would be very useful for ex-mode (see lloeki/ex-mode#31), so commands like `:'<,'>s` could be implemented.

**Comment by jazzpi** [comment]
FWIW this has been implemented in lloeki/ex-mode#160, so it isn't needed for ex-mode anymore.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
