### ISSUE TITLE
Change/delete inner tag not working correctly

### ISSUE THREAD

**Issue by isaachess** [atom/vim-mode#598]
Extension of issue #418.

Change/delete inner tag is not working like it does in vim. It should detect the tag it is in (or the _nearest_ tag, as vim does), then change/delete all content within that tag.

Currently it appears to delete everything until the next tag it finds, even if that tag isn't the same as the parent. Really buggy right now.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
