### ISSUE TITLE
Show cursor in select mode

### ISSUE THREAD

**Issue by irrationalistic** [atom/vim-mode#617]
It would be nice to see the cursor on top of the selections since using the `o` operator will switch from head to tail of the selection and it can be hard to tell where the cursor actually is.

**Comment by jacekkopecky** [comment]
Coincidentally, I just looked at this today and it's a limitation in Atom -
cursors with selections don't show up.

I found a workaround though: see
https://discuss.atom.io/t/show-text-cursor-while-selecting-text/5323/2

Then I'm not sure what the cursor will look like because I've styled it for
myself a long time ago. You'll probably want a thin cursor between
characters rather than a block cursor because if the cursor is at the end
of a selection, it's after the character rather than before it, so a block
cursor would be outside of the selection rather than part of the selection
like in VIM.

I'm typing this on a tablet, ask me for my styles if things don't look
right and I can post them when I'm on the computer again tomorrow.

**Comment by irrationalistic** [comment]
Bummer! That's pretty close though. Will have to disable it in some cases. Would love to see the styles you have if you have a chance!

**Comment by jacekkopecky** [comment]
Here's my cursor styles; no blinking, below text but above selection, bright green, same in visual mode as in insert mode. Hope it helps.
The last block of styles puts selection under the cursor so the cursor is always visible.

```
atom-text-editor.vim-mode.command-mode,
atom-text-editor.vim-mode.visual-mode,
atom-text-editor.vim-mode.operator-pending-mode,
atom-text-editor.vim-mode.insert-mode
{
  &::shadow, // shadow-DOM enabled
  &           // shadow-DOM disabled
  {
    .cursor, .cursor.blink-off {
      border: 2px solid #29ff2f;
      opacity: 1;
      z-index: -1;
      visibility: visible;
      background: none;
    }
  }
}

atom-text-editor.vim-mode.command-mode.is-focused,
atom-text-editor.vim-mode.operator-pending-mode.is-focused,
{
  &::shadow, // shadow-DOM enabled
  &           // shadow-DOM disabled
  {
    .cursor, .cursor.blink-off {
      background-color: #29ff2f;
      opacity: 1;
      z-index: -1;
    }
  }
}

atom-text-editor.vim-mode.operator-pending-mode.is-focused
{
  &::shadow, // shadow-DOM enabled
  &           // shadow-DOM disabled
  {
    .cursor, .cursor.blink-off {
      background: none;
      border: none;
      border-bottom: 10px solid #29ff2f;
      opacity: 1;
      z-index: -1;
    }
  }
}

atom-text-editor.vim-mode.insert-mode.is-focused,
atom-text-editor.vim-mode.visual-mode.is-focused
{
  &::shadow, // shadow-DOM enabled
  &           // shadow-DOM disabled
  {
    .cursor, .cursor.blink-off {
      border: none;
      border-left: 3px solid #29ff2f;
      z-index: -1;
      visibility: visible;
      opacity: 1;
      background: none;
    }
  }
}

atom-text-editor.vim-mode.replace-mode.is-focused
{
  &::shadow, // shadow-DOM enabled
  &           // shadow-DOM disabled
  {
    .cursor, .cursor.blink-off {
      border: none;
      border-bottom: 4px solid #29ff2f;
      background: none;
      z-index: -1;
      visibility: visible;
      opacity: 1;
    }
  }
}

atom-text-editor.vim-mode
{
  &::shadow, // shadow-DOM enabled
  &           // shadow-DOM disabled
  {
    .highlights .highlight.selection .region {
      z-index: -2;
    }
  }
}
```

**Comment by irrationalistic** [comment]
That's great, thanks! Would be cool to put this into a plugin that could adjust the color of the cursor to match the syntax theme.

**Comment by jacekkopecky** [comment]
Sure, go ahead. 8-)

**Comment by jacekkopecky** [comment]
Update of the above: giving the highlights a z-index of -2 doesn't work (for me anyway) - this means the cursor is shown at the end of a selection (because it's actually after it) but not at the beginning of a selection (because it's obscured by the selection).
Here's code that offsets the cursor so it's extra thick - but it doesn't show up as extra thick because half of it is obscured by the selection:
```
atom-text-editor.vim-mode.visual-mode.is-focused
{
  &::shadow, // shadow-DOM enabled
  &          // shadow-DOM disabled
  {
    .cursor, .cursor.blink-off {
      border: none;
      border-left: 6px solid #29ff2f;
      left: -3px;
      z-index: -1;
      visibility: visible;
      opacity: 1;
      background: none;
    }
  }
}
```
Feel free to re-enable blinking.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
