### ISSUE TITLE
`de` fails at the end of the file

### ISSUE THREAD

**Issue by jacekkopecky** [atom/vim-mode#622]
when the last line is not empty and the cursor is on the last character, `de` will not do anything where it should delete the last character; I may look at this because it's probably related to #555 and #581.
Also because of the same bug, `ce` at the last character of the non-empty last line behaves like `i` but should behave like `s`.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
