### ISSUE TITLE
ctrl-f and ctrl-b should extend selection

### ISSUE THREAD

**Issue by jeffschwartz** [atom/vim-mode#627]
Expected: should extend selection
Actual : clears selection

**Comment by daniloisr** [comment]
I have already fixed this, it's on this PR https://github.com/atom/vim-mode/pull/616 :smiley:

**Comment by jeffschwartz** [comment]
Most excellent! Thank you.

**Comment by bronson** [comment]
Looks fixed on current Atom and vim-mode.  Time to close this issue?

I only see one difference to Vim: when near the bottom of the page, Vim's Ctrl-F extends the selection to the exact EOF (and scrolls everything off the top of the screen) while vim-mode's doesn't do anything.

However, Vim isn't consistent.  It doesn't extend the selection to the top of the page when hitting Ctrl-B, so it acts the same as vim-mode's Ctrl-F and Ctrl-B.  Personally, I'd rather see consistent behavior than have 100% bug-for-bug compatibility with Vim.

**Comment by daniloisr** [comment]
@bronson yeah, there are still some stuffs missing, but I think that will be better if someone open a new issue for this, and close this one.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
