### ISSUE TITLE
[cdy]iW macro works like [cdy]W instead

### ISSUE THREAD

**Issue by atsepkov** [atom/vim-mode#629]
In vim, prefixing 'w' macro with 'i' applies the command to the entire word rather than the remainder of the word past the cursor. In atom with vim-mode this works correctly for lower-case 'w'. However, for upper-case 'W', the i-prefix is ignored. The upper-case 'W' uses only whitespace as delimiters rather than all punctuation like 'w', which is very useful in programming.

Here is an example of this bug, let's assume the cursor is over 'e' in the word 'key':

```
a = hash['key']      # original (assume cursor is over letter 'e')
a = hash['k']        # both vim and atom w/ vim-mode after 'dw' command
a = hash['']         # both vim and atom w/ vim-mode after 'diw' command
a = hash['k          # both vim and atom w/ vim-mode after 'dW' command
a =                  # vim after 'diW' command
a = hash['k          # atom w/ vim-mode after 'diW' command (bug)
```

**Comment by maxbrunsfeld** [comment]
Yeah, we haven't implemented the `iW` text object yet (or `i(` or `ib`). I'd love to merge a PR adding this feature. Otherwise, it's on the roadmap!

**Comment by jacekkopecky** [comment]
`iW` has been there for a while, so has `i(`, but not `ib`

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
