### ISSUE TITLE
Modifiers `k` and `j` don't work quite right with (d)elete

### ISSUE THREAD

**Issue by sknoslo** [atom/vim-mode#647]
This may be hard to explain so I'll try giving an example. Bold characters indicate the cursor position. Or an underscore, if there is no character.

Start with:

<pre>
12345
abcde
fghi<b>j</b>
</pre>

press 'dk'

Result in Vim:

<pre>
<b>1</b>2345
</pre>

Result in Atom with vim-mode:

<pre>
12345
<b>_</b>
</pre>

There are test cases that show this broken behavior, **but they do not run**, because of indentation errors with CoffeeScript. PR #386 fixes the tests, but of course, this causes Travis to report that the PR changes cause the tests to fail.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
