### ISSUE TITLE
deleting with `d` doesn't move cursor up

### ISSUE THREAD

**Issue by elclanrs** [atom/vim-mode#651]
So in Vim, when you press `d` the cursor moves one line up, so I can press `d` again, remove a line, again, remove a line... If I remember correctly this used to work in previous releases of `vim-mode` but it doesn't seem to work anymore. When I press `d` the cursor does not move up, it just stays, so pressing `d` repeatedly does not work like Vim. Any ideas? Maybe a conflict with some other plugin?

**Comment by romgrk** [comment]
Never seen that in Vim. Are you sure it isn't set in your vimrc?

**Comment by elclanrs** [comment]
Maybe I'm no explaining right, I recorded two little videos, with the same code in Atom and in Vim. I am pressing `dd` repeatedly. While in Vim the cursor moves up and I can delete another line, in Atom it just stays, I keep pressing `dd` but nothing happens.

**Atom:** http://webmshare.com/play/OnK5m
**Vim:** http://webmshare.com/play/Qm1Xa

**Comment by jacekkopecky** [comment]
Ah, same as #546 ?

**Comment by bronson** [comment]
Must be.  As far as I can tell, dd behaves the same as vim when in the middle of the file.

@elclanrs your videos are 404ing

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
