### ISSUE TITLE
Ctrl-W, O doesn't work to close other splits.

### ISSUE THREAD

**Issue by nosami** [atom/vim-mode#655]
In Vim, pressing `c-w, o` closes all other split windows apart from the one that currently has the focus.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
