### ISSUE TITLE
Numbered register 0 doesn't seem to work

### ISSUE THREAD

**Issue by tcoopman** [atom/vim-mode#660]
According to the vim docs:

```
Vim fills these registers with text from yank and delete commands.
Numbered register 0 contains the text from the most recent yank command, unless the command specified another register with ["x].
```

This doesn't seem to work with vim-mode.

**Comment by KarlPurk** [comment]
+1

I'm also having an issue with this.  The following simple use case doesn't work:

1. yank a line with yy
2. delete a line with dd
3. paste buffer with "0p

This should paste the line yanked in step 1, but instead pastes the line deleted in step 2.

**Comment by dragonxlwang** [comment]
+1 too!

It seems that "0 is not mapped to register:
https://github.com/atom/vim-mode/blob/master/keymaps/vim-mode.cson

Not sure if register 0 is implemented yet

**Comment by cpetrov** [comment]
+1

**Comment by jmacedoit** [comment]
+1

**Comment by joel1st** [comment]
+1

**Comment by capturecadet** [comment]
+1

**Comment by Maushundb** [comment]
+1

**Comment by codeluggage** [comment]
+1

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
