### ISSUE TITLE
ctrl-o in insert mode?

### ISSUE THREAD

**Issue by demon386** [atom/vim-mode#676]
Vim has ctrl-o to temporarily go from insert-mode to normal-mode.

Any plan to implement this?

**Comment by bronson** [comment]
Cute, I've never heard of this.  `:help i_CTRL-O` shows the (minimal) docs in vim: `execute a single command and return to insert mode`

**Comment by geoffwild11** [comment]
It has been a while since this thread was opened. Is this going to be implemented?

**Comment by 50Wliu** [comment]
This package is deprecated.  I would suggest looking at vim-mode-plus instead.

**Comment by bronson** [comment]
True, and for ctrl-i and ctrl-o, you'll want to look at t9md's cursor-history package.  Works great.

**Comment by bronson** [comment]
Ah, insert-mode ctrl-o.  Sorry, read too fast.

vim-mode-plus has a partial implementation for insert mode ctrl-o.  If it doesn't work as well as you'd like, definitely file an issue.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
