### ISSUE TITLE
Regression: repeating a 'cw' just kill the second word.

### ISSUE THREAD

**Issue by np** [atom/vim-mode#678]
0.47 works while 0.48 and 0.49 have this issue.

How to reproduce:

```
foo foo
```

Hit 'cwbar<ESC>' then go to foo and hit '.', it kills the word foo instead of putting bar instead.

**Comment by maxbrunsfeld** [comment]
@np what version of Atom are you using? The newest versions of vim-mode require a fairly new version of Atom. Can you check if the error persists after upgrading to 0.201?

**Comment by np** [comment]
Atom: 0.188.0

Could you specify a lower bound in the package.
I gave 0.201 a try but I'm hitting a crash at startup...

**Comment by maxbrunsfeld** [comment]
@np have you created or found an issue on atom/atom for the crash that you're experiencing? I would like to take a look at it.

**Comment by gittyupagain** [comment]
I've been hitting this for a while now too, and I'm using Atom 0.209. I've only seen the problem when a file has not yet been modified. That is, if the first modification is from 'cw', the '.' afterwards will eat the word instead of replacing it with the specified change. I just tried some more tests, and it isn't limited to 'cw'. You will likely see it when using '.' after most change or insertion commands (again, only when it is the first modification to the file). I didn't see the problem if the first action was a deletion.

**Comment by maxbrunsfeld** [comment]
@gittyupagain are you using the latest version of `vim-mode` (0.52)?

**Comment by gittyupagain** [comment]
Yes. Are you not seeing it?

**Comment by maxbrunsfeld** [comment]
@gittyupagain I see it now. In a certain case, we would fail to detect changes in the history. Fixing...

**Comment by maxbrunsfeld** [comment]
Can you try again with version 0.53?

**Comment by gittyupagain** [comment]
Yes, that works. Thanks!

**Comment by maxbrunsfeld** [comment]
Great. Thanks for checking in about this.
