### ISSUE TITLE
`yi/` opens search

### ISSUE THREAD

**Issue by jazzpi** [atom/vim-mode#680]
I tried yanking the contents of a RegEx using `yi/`, which opened search. After that I checked vim, which didn't open search but also didn't yank the text enclosed by `/` (that would be great).

**Comment by bronson** [comment]
So, you're asking for a // text object?

I agree that, if Atom doesn't recognize a text object, it should probably do nothing.  Like vim.

**Comment by jazzpi** [comment]
Yes, it should probably do nothing - and not open search.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
