### ISSUE TITLE
S-" in visual mode should surround the selected character in quotes

### ISSUE THREAD

**Issue by westoque** [atom/vim-mode#682]
Basically, a feature like surround.vim.

You can select any character(s) in visual mode, then do S-(N), where N is any character, to surround the selected character(s) in N.

**Comment by bronson** [comment]
Have you seen https://atom.io/packages/vim-surround?

If it's not in core vim, does it belong in vim-mode?

**Comment by westoque** [comment]
@bronson Thanks. I didn't see that.

I agree. If it doesn't belong in core vim, then it shouldn't be in vim-mode.

However, it would be weird having an atom plugin that depends on another atom plugin. They should be exclusive IMO.

**Comment by bronson** [comment]
People are working on atom-to-atom package dependencies: https://github.com/atom/atom/issues/2412

You wouldn't like this?  Personally, it sounds OK to me...  Better than packages duplicating each others' code anyway.

**Comment by westoque** [comment]
@bronson I actually do like it since we only have to install one package.

We don't have to mimic "core" vim exactly since this is in atom.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
