### ISSUE TITLE
ctrl-e breaks visual selection just before cursor leaves screen.

### ISSUE THREAD

**Issue by kWhittington** [atom/vim-mode#683]
When performing a visual selection (`v` or `V`), then scrolling the page with `ctrl-e` or `ctrl-y`, the selection will be destroyed once the cursor nears the edge of the screen.

I've performed a downward block selection (`V`) (so the cursor is on the bottom of the selection) with the cursor on line 50. After scrolling with `ctrl-y`, once line 55 left the screen, the selection breaks and the cursor reappears at the beginning of line 51.

When doing the opposite (upward selection and scrolling upward), I placed the cursor of the block selection on line 20. After scrolling with `ctrl-e`, once line 16 left the screen, the selection breaks and the cursor reappears at the beginning of line 20.

**Comment by maxbrunsfeld** [comment]
Thanks for catching that @kWhittington.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
