### ISSUE TITLE
open vertical and horizontal splits from tree view using vim shortcuts

### ISSUE THREAD

**Issue by sheldonkwok** [atom/vim-mode#685]

**Comment by bronson** [comment]
You mean typing <kbd>V</kbd> when the tree view is focused would open the selected file in a vertical split?  Same for H and horizontal split?

**Comment by sheldonkwok** [comment]
ctrl-w v for vertical and ctrl-w s for horizontal

**Comment by bronson** [comment]
Ah, I thought you were asking for nerdtreeish functionality.  You'd just like Vim's regular bindings to apply there.  Makes sense.

That invites the question of "how much monkeypatching of other packages is acceptable for vim-mode?"

**Comment by bronson** [comment]
One way to solve it might be to create a `tree-view-vim-mode` package that layers vim's keybindings on top of tree-view.  That at least isolates the monkeypatching into a small, easy-to-disable package.  Hopefully it wouldn't explode into an n+1 problem where there's a _package_-vim-mode for every installed package.  :)

**Comment by sheldonkwok** [comment]
Ah that works too. Should've noticed that the modifications were for the editor only. Thanks!

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
