### ISSUE TITLE
repeat-prefix to stack with Atom's operations

### ISSUE THREAD

**Issue by atsepkov** [atom/vim-mode#697]
I'm not sure if this is doable without great redesign, but I often find myself using the number prefix to repeat a macro several times in vim. I know it's not currently possible to add macros to vim-mode, but there are certain equivalents already available in Atom directly that could benefit from stacking with the repeat-prefix.

For example, the comment/uncomment operation `mod+/` toggles the comment for the line/selection. In vim I had the same macro bound to `,#`, so I simply created a new mapping in Atom. It works fine for selections (visual mode), but I can't tell Atom to comment the next 10 lines via `10,#` because repeat-prefixes don't stack with other Atom macros. I'm not sure if this request would be better addressed by ex-mode plugin (because they support regex replacements of the form ,+10s/^/#/ and it may be easier to map that to a repeat-prefix), let me know if I should ask them about this instead.

**Comment by maxbrunsfeld** [comment]
Thanks for raising this issue; I'd really like to support this. You're right that it would take a fair amount of work. I think the best way to do it would be to add some new API to Atom core that would allow querying the history of commands that were run on an editor.

One thought that comes to mind is that we could extend the history API in `text-buffer` to allow storing arbitrary metadata on each history entry. We could use that in Atom to store the name of the command that was run.

I think that if we do implement this, it should probably be part of `vim-mode`, not `ex-mode`, because the functionality for handling repeats and counts are in `vim-mode`.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
