### ISSUE TITLE
How to map leader+key to pending motion operations

### ISSUE THREAD

**Issue by lmartins** [atom/vim-mode#706]
One command I used all the time was change inside something, usually inside quotes or brackets. So often that I had that mapped to  leader + c. 

Is there any way I can achieve something similar in Atom's Vim mode?

Cheers.

**Comment by fullofcaffeine** [comment]
+1, I'd like to create a shortcut with leader,b to switch "buffers" and leader,f to find files (Atom's command+T). Any hints?

**Comment by bronson** [comment]
@fullofcaffeine Leader is just a convention.  If you want <kbd>space</kbd> to be the mapleader, then adding this to keymap.cson should work:

```cson
'atom-text-editor.vim-mode.command-mode':
  'space b': 'fuzzy-finder:toggle-buffer-finder'
  'space f': 'fuzzy-finder:toggle-file-finder'
```

@lmartins I don't understand...  It sounds like you want to map leader+c to be the same as c+i... but that doesn't save any keystrokes!  What is the exact vim mapping you want to emulate?

**Comment by lmartins** [comment]
@bronson Scott, thank you for your feedback on this. 

In Vim I had the following mappings:
```
" ChangeInside
nnoremap <silent> <Leader>c :ChangeInsideSurrounding<CR>
nnoremap <silent> <Leader>C :ChangeAroundSurrounding<CR>
```
This is calling a function that I assume will work for any surroundings (single quote, quotes, brackets, etc).

I was looking for a easier way to trigger the change inside quotes and/or single quotes with the same shortcut. Is this possible?

The other use case was what you already described to @fullofcaffeine , thanks :)

**Comment by bronson** [comment]
:ChangeInsideSurrounding doesn't exist in vim...  I guess you're using this plugin?

https://github.com/briandoll/change-inside-surroundings.vim

If so then yes, that will require writing an Atom plugin.  Which, I'm happy to say, is actually not too hard.

**Comment by lmartins** [comment]
Thank for your feedback on this. Closing now.

**Comment by willopez** [comment]
atom calls "command" mode  "normal" mode, so custom bindings will looks like this: 
```
'atom-text-editor.vim-mode.normal-mode':
  'space b': 'fuzzy-finder:toggle-buffer-finder'
  'space f': 'fuzzy-finder:toggle-file-finder'
  'space p': 'core:save'
```

**Comment by lmartins** [comment]
Thanks @willopez that helped.

**Comment by michaelghinrichs** [comment]
Hey @lmartins vim comes out of the box with the ability to change inside!

given this line of javascript:
```js
let example = 'change-me';
```

you can do the following
```
f'ci'changed!
```
^^ I usually misunderstand what this actually means so I will break it down for ya

`f` finds the next character on the current line, in this case it is `'` (shift f, `F` searches backwards)
`ci'` is the vim function that means `change inside the quote tag` (you can do most things that wrap)
`changed!` is the string i chose to replace it with as you are now in insert mode

and the fun doesn't stop there! Check this one out!

```js
  {
    form: 'observation',
    fields: ['name', 'number', 'description', 'id'],
    asyncValidate,
  },
```
let's say you have this structure ^^

As long as your cursor is anywhere inside of the braces`{}` you can just do `ci{` and you will see this:

```js
{}
```
with your cursor loaded and ready to fire in `insert` mode

Because of how awesome ViM is i bet you can guess what `di{` does!

And since I am just going full blog post on this comment, here is a great stack overflow post with some great basic vim commands!
http://stackoverflow.com/questions/1276403/simple-vim-commands-you-wish-youd-known-earlier

Cheers! :)

**Comment by lmartins** [comment]
Hey Michael, I've spent a long time trying to move from Atom to Vim just for things like this. Im glad Atom Vim support is improving as I believe that merging Vim features with a modern UI like Atom is the way forward. 

Many thanks for your comments and useful resources. Cheers ;)

**Comment by michaelghinrichs** [comment]
course! i completely agree, vim-mode is fantastic for pairing with my co-workers that don't know vim, which is what i think is the one downfall of only doing vim :(

**Comment by dineshbhosale** [comment]
Thanks :+1:
