### ISSUE TITLE
Move to end of file?

### ISSUE THREAD

**Issue by ryanphuang** [atom/vim-mode#707]
I'm trying to use the normal vim keymap to jump to the end of file. But couldn't find it. `g g` is mapped to "move to the start of file", and `G` is mapped to "move to beginning of line". But in vim, `G` is used to "jump to the end of file" ([Moving around](http://vim.wikia.com/wiki/Moving_around)). I also didn't find a `MoveToEndOfFile` method like `MoveToStartOfFile` in `motions/general-motions.coffee` that I can use to replace the mapping in `vim-mode.cson`.  I'm not familiar with CoffeeScript, any pointer in how to implement the move to end of file is appreciated!! (Currently I'm using `command-down` key).

Thanks!

**Comment by maxbrunsfeld** [comment]
@stormspirit By default `G` should move to the end of the file. What are you seeing it do? If it isn't working, could you share the output of the keybinding-resolver (`Key Binding Resolver: Toggle` from the command palette) when you type that key?

**Comment by stormspirit** [comment]
This is the screenshot, it looks like it recognized it as lower-case 'g' instead of 'G' (The caps lock is on, I made sure that). Also, I see that caps lock is recognized first ("Key Binding Resolver: capslock"). 


![screen shot 2015-06-25 at 4 46 56 pm](https://cloud.githubusercontent.com/assets/2121412/8368038/fe6c1678-1b59-11e5-907e-0f58ac7eee7f.png)

**Comment by stormspirit** [comment]
The behavior is that pressing 'G' does nothing, (because it thinks it's a 'g' and waiting for next key?)

**Comment by bronson** [comment]
Does G work when pressing <kbd>shift-g</kbd>?  It's just capslock that causes it to go wrong?

**Comment by stormspirit** [comment]
shift-g works!!

**Comment by signothefish** [comment]
@stormspirit, how did you get shift-g to work?  I have this in my vim-mode.cson file:
'g g': 'vim-mode:move-to-start-of-file'

But there is no key mapping for 'G'. In fact, my key binding resolver comes up empty for both 'g' and 'shift-G'.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
