### ISSUE TITLE
Is there a way to create a custom operator?

### ISSUE THREAD

**Issue by caleb** [atom/vim-mode#725]
Is `vim-mode` designed to allow custom operators? I would like to develop a plugin to emulate [`vim-exchange`](https://github.com/tommcdo/vim-exchange), and I was looking into the service provided by `vim-mode`.

However, at first look it seems that all the methods I would use like `registerOperationCommands` and `pushOperations` (in `lib/vim-state.coffee`) are marked as private.

Is there a way to create custom operators that's more sanctioned, or would I have to hook into these private methods.

Thanks for all your work on vim-mode, It makes atom so much more ergonomic as a text editor.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
