### ISSUE TITLE
visual + home/end of line motion

### ISSUE THREAD

**Issue by davibe** [atom/vim-mode#730]
I know this is not very vim-hacker feature but with macvim i was used to put the cursor in the middle of the line (somewhere interesting), hit "v", and move to the end of the line with CMD+Right (end-of-line on macs). In this case the cursor would correctly move to the end of the line while enlarging the visual selection.

If i do this with atom vim-mode the cursor moves but i loose selection. Same goes for moving with CMD+Up/Down and i think its wrong.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
