### ISSUE TITLE
"x" can delete end of line

### ISSUE THREAD

**Issue by davibe** [atom/vim-mode#731]
if i use CMD+Left to reach the end of the line instead of "$" the cursor gets past the last character up to the EOL character. At this point hitting "x" deletes the '\n' and the next line is sucked up in the current one.

This may not be strictly vim-mode related

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
