### ISSUE TITLE
Implement zO

### ISSUE THREAD

**Issue by eesdil** [atom/vim-mode#733]
Would be great to have zO to open everything under the current fold.

**Comment by morenoh149** [comment]
I'd like to be assigned this. And also given some direction on where to start looking.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
