### ISSUE TITLE
if text object isn't recognized, nothing should happen

### ISSUE THREAD

**Issue by bronson** [atom/vim-mode#734]
If the user types `vix`, nothing should happen.   `x` is not a valid text object.

Vim does nothing.  Atom, alas, deletes the character under the cursor.

Inspired by https://github.com/atom/vim-mode/issues/680

**Comment by jacekkopecky** [comment]
This is a wider issue: vim-mode doesn't realize it's encountered an unrecognized key sequence, and cancel it. Above, it's `ix` in visual mode. In #760, it's `ci3`; therefore while in VIM `ci3w` behaves as `w`, having cancelled `ci3`, in vim-mode it behaves as `c3w`, ignoring the `i`. This is also part of #741.

**Comment by bronson** [comment]
So it's just a natural side effect of using multi-key keybindings?  You know of any hope for fixing it?  (just curious)

Binding every keypress would be a brute-force way of getting there but that might get out of hand.

```cson
'atom-text-editor.vim-mode.operator-pending-mode, atom-text-editor.vim-mode.visual-mode':
  'i x': 'vim-mode:reset-command-mode'
  'i X': 'vim-mode:reset-command-mode'
  'i y': 'vim-mode:reset-command-mode'
  'i Y': 'vim-mode:reset-command-mode'
  'i z': 'vim-mode:reset-command-mode'
  'i Z': 'vim-mode:reset-command-mode'
  etc etc etc
```

Sorta like you did with ctrl-r.  :)

**Comment by jacekkopecky** [comment]
Hopefully there's no need for brute force here, even though I enjoyed employing it with ctrl-r. 8-)

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
