### ISSUE TITLE
visual selection expands folds

### ISSUE THREAD

**Issue by bronson** [atom/vim-mode#735]
Create some folds.  Now try moving a visual selection across the folds.  You can't!  The visual selection opens all the folds it comes near.

Folds work correctly when the selection is created using the mouse.

Vim's visual selection allows folds to remain closed.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
