### ISSUE TITLE
auto-indent gets confused by multi-line (indented) function calls

### ISSUE THREAD

**Issue by ssfrr** [atom/vim-mode#742]
Here's some code I'm working on that doesn't get indented properly. This is the state it's in after selecting all of it and pressing `=`:

``` c
void HTOrientation_process() {
    if(state == HTORIENT_STATE_ORIENTING) {
        bool updated = IMURead(&Mpu);
        if(updated) {
            IMUData data = getData(&Mpu);
            MadgwickAHRSupdateIMU(
                data.gyro.x,
                data.gyro.y,
                data.gyro.z,
                data.accel.x,
                data.accel.y,
                data.accel.z);
                // print_imu_data(data);

                Quaternion orientation = {q0, q1, q2, q3};
                if(OnOrientationUpdate) {
                    OnOrientationUpdate(orientation);
                }
            }
        }
    }
```

As you can see everything after the multi-line function call with indented arguments it doesn't reset the indent level to the level of the function call.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
