### ISSUE TITLE
period (`.`) after backspace in insert mode doesn't redo properly

### ISSUE THREAD

**Issue by ssfrr** [atom/vim-mode#743]
To reproduce:

press `i` then backspace a few times then `esc`
move somewhere else and press `.`

You expect the same number of removed characters to be removed again but they are not.

It seems that any deletions before the initial insert point are ignored.

I suppose it could implement classic vi, but then it wouldn't let you delete before the insert point in the first place.

**Comment by bronson** [comment]
Yep, it's true.  Might be related to https://github.com/atom/vim-mode/pull/740 (but don't hold up 740 for this!).

I was pleasantly surprised that nothing happens...  I was expecting wild deletions.  :)

**Comment by vaibhkrishan** [comment]
Hi,
I faced a similar issue though not exactly same. Goes like this:
1. select some text using visual mode.
2. delete it using "d".
3. go somewhere else and press ".".
4. It repeats the action where it happened last not where your cursor is, while in vim it happens where the cursor is.

**Comment by bronson** [comment]
Hi, the fix (by @jacekkopecky) should be in the vim-mode-next package.  If you want to try it (disable vim-mode, install vim-mode-next, and restart Atom), I'd be curious to hear the result.  You can disable vim-mode-next any time of course.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
