### ISSUE TITLE
Connot move to the last character of the line with $, even with softWrap disabled

### ISSUE THREAD

**Issue by sammahfoud** [atom/vim-mode#746]
I have disabled softWrap, but still cannot use $ or 0 to move to the first/last character of a line.

**Comment by 50Wliu** [comment]
What versions of Atom and vim-mode are you using?

**Comment by sammahfoud** [comment]
I'm using Atom 1.0.0 and vim-mode 0.54.0
In safe mode, vim-mode seems to be enabled in the Settings, but it doesn't work at all

**Comment by 50Wliu** [comment]
My apologies, totally forgot that this was on vim-mode (so safe mode would disable vim-mode).
Can you then paste the output of `apm list --installed`?  Thanks.

**Comment by sammahfoud** [comment]
Thank you for your help, here is the output :

/home/mahfoud/.atom/packages (3)
├── desert@0.2.0
├── dracula-theme@0.7.6
└── vim-mode@0.54.0

On Thu, Jul 9, 2015 at 12:44 AM, Wliu <notifications@github.com> wrote:

> My apologies, totally forgot that this was on vim-mode (so safe mode would
> disable vim-mode).
> Can you then paste the output of apm list --installed? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/vim-mode/issues/746#issuecomment-119760553>.
>



-- 
Mahfoud Sidi Ali Mebarek
+213 555 88 39 61

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
