### ISSUE TITLE
Show more vim-mode status in the status bar

### ISSUE THREAD

**Issue by smaili** [atom/vim-mode#751]
Just like with searching, add a bottom input bar when typing the line number for going to a specific line.  Very useful so you can see what you're typing, and is also the default functionality of vim.

**Comment by bronson** [comment]
In other words, show the operator-pending text in the status bar while typing.  :)

I'd like that.

**Comment by msmaili** [comment]
In addition, when searching for a pattern, if none could be found, show a message, such as:

![not-found](https://cloud.githubusercontent.com/assets/4451986/8597603/5df66efc-260b-11e5-8c7c-1c938677c61c.png)

Also, if you reach the end of the file while searching and go back to the top, also show a message:
![back-to-top](https://cloud.githubusercontent.com/assets/4451986/8597701/d2203b82-260b-11e5-8bc1-2c174a6b9f23.png)

I hope you don't mind Scott that I've added these here as well since they all are related to search status.  If you'd rather break them into multiple let me know.

**Comment by bronson** [comment]
Looks great.  Maybe update the title, something about showing more vim-mode status in the status bar?  Not just what mode you're in.

**Comment by caiocutrim** [comment]
Great Idea, I almost open a new Issue about that :), but someone thinks first XD

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
