### ISSUE TITLE
add last edited ('.) and last position ('') marks

### ISSUE THREAD

**Issue by motiko** [atom/vim-mode#756]
In vim  '. will take you to last edit mark and '' to last visited mark . 
I couldn't make it work in vim-mode maybe I'm just missing something.
Would be happy to assist in implementing this but still don't have much experience in Atom so if someone can give me a little push in the right direction where to start..

**Comment by bronson** [comment]
I can suggest how I would approach this.  FWIW...

First, figure out how https://atom.io/packages/goto-last-edit knows where the last edit is.  Also, glance through [general-motions.coffee](https://github.com/atom/vim-mode/blob/master/lib/motions/general-motions.coffee) to see how motions work and if there's anything that is close to this in functionality.

Second, now that you know everything, write the motion, write some tests, and bind it to `'.`.

Third, fire off a pull request.  Profit!

Then, figure out how https://atom.io/packages/last-cursor-position works, make a motion for `''` and profit 2X.

Sounds like fun.  Ask on Slack or follow up here if you have questions.

**Comment by motiko** [comment]
Wow thanks a bunch. 
Looks like i have some work to do :octocat:

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
