### ISSUE TITLE
Undo Branches

### ISSUE THREAD

**Issue by mrthebob** [atom/vim-mode#775]
One very useful feature in vim is undo branching.  I'm sure this may be a more complex feature, but it can be a real life saver.  Let's say I make some changes, undo them, and then start typing again, only to realize that I needed some of those other changes.  Without undo branches, those changes are gone.  With them, I am free from worry about losing work! :)

See: http://vim.wikia.com/wiki/Using_undo_branches

**Comment by jacekkopecky** [comment]
Oh, I had no idea about this feature! Cool!
But I think it would be better in atom rather than in vim-mode. I don't know if a package could do it, or if it would need to go in the core.

**Comment by mrthebob** [comment]
Yeah, it's a great feature.

I was wondering the same thing - if it's something that would be better in Core...

**Comment by mrthebob** [comment]
Opened a ticket there.  Will have to see what they say: https://github.com/atom/atom/issues/7917

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
