### ISSUE TITLE
Column not kept while down/up moving in visual mode character-wise.

### ISSUE THREAD

**Issue by t9md** [atom/vim-mode#788]
When moving up and down in visual-mode charwise.
Cursor's column not kept.

Reproduce
1. enter `v` on `l` of `long` on 1st line(column=22).
2. `jj`
3. cursor is positioned `g` of length which is last column of 2nd line(I want to be column=22).

```
very very very very long line
short line
middle length of line
```

Atom's native up down have no issue with same operation(shift-up/down keep cursor column).

It seems cursor's column is adjusted to minimum(leftmost) column which past.

**Comment by jacekkopecky** [comment]
Ah, first guess: the cursor needs a goal column there, and needs to heed it.

**Comment by t9md** [comment]
I fixed on my folked vim-mode, by restoring `goalColumn` after `cursor.moveRight()`, `cursor.moveLeft()` which is happened within `Motion.select()` method to adjust cursor position.  
This adjustment is needed to achieve visual-mode selection but side movement automatically clear the goalColumn of cursor, so we need to manually restore goalColum in case side-movement is internally happened in vim-mode.

The fix approach would be same on official vim-mode, but code is very different I can't PR as-is and won't, but I put this note(and linked my commit) for someone try to fix this issue in future.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
