### ISSUE TITLE
Auto insertion should be disabled when in replace mode (SHIFT + R)

### ISSUE THREAD

**Issue by mdaffin** [atom/vim-mode#792]
When in replace mode (via `SHIFT + R`) entering `"` causes the current (as expected) as well as next character (unexpected) to be replaced with two `"`

This happens with and other character with a corresponding closing character; `{}`, `[]`, `'` etc. and only when atom would normally insert the closing character in insert mode.

For example, given ![image](https://cloud.githubusercontent.com/assets/171232/8871017/2254f928-31ea-11e5-97f4-fd7c31cd75c7.png), pressing `SHIFT + R` then `"` you end up with:
![image](https://cloud.githubusercontent.com/assets/171232/8871025/2e3a3da2-31ea-11e5-8855-a5e024b7066b.png)

The next character will replace the second `"` as expected, but the second `"` should have never been inserted.

The expected output is ![image](https://cloud.githubusercontent.com/assets/171232/8871117/e0cf5e02-31ea-11e5-9c5a-58311aa0e15d.png)

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
