### ISSUE TITLE
`dd` line deletion on last line

### ISSUE THREAD

**Issue by smaili** [atom/vim-mode#801]
Couple issues when trying to remove the last line via `dd`.

1) If the last line is completely blank and `dd` is pressed, nothing happens.

2) If the last line is not blank and `dd` is pressed, the line's contents are removed but the line itself is not.

**Comment by bronson** [comment]
yep, https://github.com/atom/vim-mode/issues/546

I have a branch around here somewhere that tried to fix this but it ended up spiraling out of control.  I keep meaning to go back and try again.

**Comment by bronson** [comment]
Looks like https://github.com/atom/vim-mode/issues/681 is another dupe.

**Comment by maxbrunsfeld** [comment]
Thanks @bronson. Closing this out in favor of #546.

**Comment by maxbrunsfeld** [comment]
Actually, let's keep this issue around instead, since it has the most detail.

**Comment by mleeds95** [comment]
I found one way to fix this but it's kinda messy: modify `MoveToRelativeLine.moveCursor` to go to the last character of the row above if it's on the last line and modify `Motion.moveSelectionLinewise` to set the buffer range columns, not just rows. However it would be cleaner to modify `Delete.execute` to use `Selection.deleteLine()` instead of `Selection.deleteSelectedText()` in this situation.

**Comment by redbmk** [comment]
Even without vim-mode enabled, I've noticed that when you save a file in atom, if the last line is not blank, it adds a blank line.

So, even with this fix in place, it looks like once you save the file you might get a new line anyway... Is that a bug or on purpose?

**Comment by j127** [comment]
There seems to be a related problem with `cc`. Both `cc` and `dd` don't work on the last line, if it's blank. Sometimes I use `cc` in Vim to enter insert mode in a new, blank file, but it doesn't work in Atom, because that first blank line is also the last.

> it looks like once you save the file you might get a new line anyway... Is that a bug or on purpose

You should be able to override that with [this package](https://atom.io/packages/editorconfig) and a [.editorconfig file](http://editorconfig.org/):

    insert_final_newline = false

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
