### ISSUE TITLE
Multi-cursor keyboard shortcut on Windows 8.1?

### ISSUE THREAD

**Issue by janacm** [atom/vim-mode#804]
I am able to use multi-cursors by ctrl-clicking, but I want to be able to use multiple cursors by highlighting a word, and the pressing ctrl+d. Currently, ctrl+d moves the cursor to the beginning of the line. Is there any keyboard shortcut for using multi cursors in vim mode?

**Comment by bronson** [comment]
Vim has quite a few normal-mode bindings that conflict with Atom's bindings on Windows and Linux (Macs, thanks to the command key, don't have as many).

Often the way to fix this is to just go to insert mode.  Insert mode should give you almost the full Atom experience.

That said, if you'd rather have Atom's binding than Vim's, you can unset it.  For example, throw this in your keymap.cson file to use atom's ctrl-d behavior:

```cson
'atom-text-editor.vim-mode:not(.insert-mode)':
  'ctrl-d': 'unset!'
```

This should probably go in the readme or faq or something...  Feel free to issue a documentation PR if you can find a logical place for it.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
