### ISSUE TITLE
Motion with shift + { and shift + } doesn't work properly

### ISSUE THREAD

**Issue by kozie** [atom/vim-mode#807]
I have tried multiple files with different languages/syntax.

Using shift + } doesn't always seem to work while shift + { sometimes jumps to the previous empty line and somewhere in the middle of a code block.
In a coffeescript file (for example) the cursor jumps back and forth to the beginning and end of the file.

I myself and most probably a bunch of other 'VIM' users heavily depend on this functionality as it makes the user able to navigate very quickly through code. I really, really miss this functionality as in going back to gvim itself.

**Comment by bronson** [comment]
Agreed, I miss it too.

Technically base vim doesn't get shift+} right either...  it needs Ruby, Python, CoffeeScript, etc language files to override the binding and add some smarts.

I'm not sure vim-mode has a plan on how to allow per-language customization yet.  It's time to start that discussion.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
