### ISSUE TITLE
ctrl-w s, v different, it won't keep scroll ratio.

### ISSUE THREAD

**Issue by t9md** [atom/vim-mode#815]
Currently it directly depending on Atom's `pane:split-xxx` commands.
And its not sync scroll ratio of original editor after split.

```
  'ctrl-w ctrl-v': 'pane:split-right'
  'ctrl-w v': 'pane:split-right'
  'ctrl-w ctrl-s': 'pane:split-down'
  'ctrl-w s': 'pane:split-down'
```

I sent PR for this to be improved.

https://github.com/atom/atom/pull/8228

Expected behavior is how Vim behave like following.
- Sync scroll ratio for splitted pane.
- Won't activate splitted pane.

For activation, it will partially achieved by using `split-up` and `split-left` but change current pane which have multiple item.
I want new splitted Pane with single item open down or right and wont' activated.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
