### ISSUE TITLE
Adding g$ and g^ functionality 

### ISSUE THREAD

**Issue by thaldyron** [atom/vim-mode#817]
While j and k seem to work like gj and gk, currently ^ and $ jump to the first resp. last character of the buffer line. There doesn't seem to be a way to jump to the first/last character of the screen line when soft wrap is enabled.

**Comment by thaldyron** [comment]
Something like this should work, but it only works for g$ and neither for g^ nor g0: 

`'atom-text-editor.vim-mode:not(.insert-mode)':
  'g^': 'editor:move-to-beginning-of-screen-line'

'atom-text-editor.vim-mode:not(.insert-mode)':
  'g0': 'editor:move-to-beginning-of-screen-line'

'atom-text-editor.vim-mode:not(.insert-mode)':
  'g$': 'editor:move-to-end-of-screen-line'`

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
