### ISSUE TITLE
Cursor missing in line selection mode

### ISSUE THREAD

**Issue by voltrevo** [atom/vim-mode#820]
In real vim, I often combine `V` with `%` to cleanly grab blocks of code by selecting whole lines and jumping to the other end of the block. This plugin seems to not have a cursor in line selection mode and `%` seems to have no effect during line selection.

**Comment by jacekkopecky** [comment]
Yes, by default Atom hides the cursor when selecting; see #617 for tips on how to show the cursor.

When you see the cursor, you'll see why `%` doesn't work as expected: in linewise visual mode, the cursor goes at the beginning of the **next** line - the end of the selection - so it's no longer where you expect it to be and `%` can't work.

It's a current limitation in Atom that it doesn't support linewise selection with a cursor elsewhere than at the beginning or the end of the selection. I have a few ideas for how this could be addressed.

**Comment by voltrevo** [comment]
Interesting. Thanks for getting back to me.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
