### ISSUE TITLE
Undoing a paste leaves the cursor in the wrong place

### ISSUE THREAD

**Issue by bronson** [atom/vim-mode#821]
Hitting `p` `u` leaves the cursor one position to the right.  If you keep hitting `pu`, the cursor eventually reaches the rightmost column of the line.

In vim, the cursor doesn't move at all.

**Comment by jacekkopecky** [comment]
Yes, undo in Atom currently puts the cursor in a different place than VIM
does. It's on my radar because it's been bugging me too. I think it's not
just undoing P.

Ooh, a quick thought that I cannot check right now - does vim-state fail to
move the cursor after undo to match the cursor move after other commands?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
