### ISSUE TITLE
Missing Support for Bar Motion

### ISSUE THREAD

**Issue by tjfwalker** [atom/vim-mode#824]
One ought to be able to type `<number>|`, e.g., `80|`, and, as a result, have the text cursor move to that number, in this case the 80th, column.

for reference: http://stackoverflow.com/questions/9953082/how-to-jump-directly-to-a-column-number-in-vim

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
