### ISSUE TITLE
"Newline Above/Below" breaks on normal mode

### ISSUE THREAD

**Issue by chibicode** [atom/vim-mode#829]
Hi, I'm on version 0.58.0, and recently `Editor: Newline Below` command started breaking only on normal mode. The last character on the line gets moved down to the next line:

![](http://cl.ly/image/3J2L0q1R2w08/Screen%20Recording%202015-08-18%20at%2005.18%20PM.gif)

This doesn't happen on insert mode / vim mode disabled. This used to work fine on vim-mode normal mode, but it started breaking recently. Not quite sure if this is Atom's issue or vim-mode's issue (I'm on Atom 1.0.7).

**Comment by maxbrunsfeld** [comment]
/cc @jacekkopecky 

Maybe we need to move back to constraining the cursor position within the line explicitly, after each command, rather than doing it inside of an `onDidChangeCursorPosition` observer.

**Comment by jacekkopecky** [comment]
Seems to be the same issue as #806, addressed in #827.

**Comment by chibicode** [comment]
Actually, just noting that `Newline Above` fails as well.

```
AAA
BBB
```

If I run `Newline Above` when the cursor is at any of the `B`'s, then this is the result:

```
AA
A← cursor is here
BBB
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
