### ISSUE TITLE
end of line command ($) while in visual mode 

### ISSUE THREAD

**Issue by jpanda109** [atom/vim-mode#833]
Using the $ command while in visual mode incorrectly highlights the newline character at the end of the line instead of only the characters up til there.

Atom: 1.0.7
OS: Windows 10
vim-mode: 0.58.0

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
