### ISSUE TITLE
Inconsistency in *at and *it behavior

### ISSUE THREAD

**Issue by naorunaoru** [atom/vim-mode#835]
For example, let's take this snippet:

```
<ul>|
  <li>text1</li>
</ul>
```

(`|` is the position of the cursor)

On `vat` Vim will select everything inside `<ul />` and Atom with vim-mode will only select between `>` after `<ul>` and `<` in first `<li />`.

Another inconsistency:

```
<|ul>
  <li>text1</li>
</ul>
```

Vim: `vat` selects entire `<ul />`, `vit` selects its contents.
Atom+vim-mode: `(v|c|d|y)(a|i)t` do nothing.

More information about expected behavior: `:help tag-blocks` in Vim.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
