### ISSUE TITLE
inconsistent timeout for multi-key commands

### ISSUE THREAD

**Issue by jacekkopecky** [atom/vim-mode#841]
vim-mode composes commands from multiple keys, with no timeout. `c3w` can be pressed with any delays. However, `gUG` can't because `gU` is an atom multi-key binding, so atom's timeout (default 1s) applies. That's an inconsistency, and I just got bit by it (when working with one hand and distracted, I couldn't get `gUG` to work properly).

Can anyone think of any issue if we tried to do all composing in vim-mode, without relying on atom multi-key bindings?

One issue I can think of is in packages such as vim-surround that integrate with vim-mode and also use multi-key bindings; to avoid using multi-key bindings, vim-mode would need to export an API for adding commands from multiple key bindings combined by vim-mode.

This issue is also related to #764 and #781 - cancelling unrecognized key combinations would be much easier if vim-mode was in full control of it.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
