### ISSUE TITLE
Option to enter normal mode on save

### ISSUE THREAD

**Issue by DylanBruzenak** [atom/vim-mode#843]
Currently I use this, and it works fine. Could be enough, but maybe useful to include in the doc or something ?

in init.coffee:

``` coffee
atom.workspace.observeTextEditors (editor) ->
 editor.getBuffer().onDidSave ->
   editorElement = atom.views.getView(atom.workspace.getActiveTextEditor())
   atom.commands.dispatch(editorElement, 'vim-mode:activate-normal-mode')
```

**Comment by dentarg** [comment]
thanks @DylanBruzenak :) your snippet helped me get the same behavior I have [in Sublime Text](https://github.com/dentarg/gists/blob/master/gists/sublime-text/stop_insert_on_save.py)

**Comment by despairblue** [comment]
@DylanBruzenak awesome. I wonder if there is an event that is triggered when a pane loses focus. I tend to switch to another pane thinking I'm in normal mode.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
