### ISSUE TITLE
Suggestions for / and ? search commands.

### ISSUE THREAD

**Issue by JesseLeite** [atom/vim-mode#852]
This is the input styling for / and ? commands:
![1](http://i.imgur.com/ccW1cxS.png)
Why not something more native-to-Atom feeling like this, or at least a simplified version of this?
![2](http://i.imgur.com/7waFzJH.png)

Also, a few more related suggestions:
1. I think "Use Clipboard As Default Register" setting is a great opt-in Vim+Atom integration.  Similarly, it may be nice to have a "Use Atom's Default Search" opt-in setting for mapping Atom's default find-and-replace functionality to `/` and `?` vim commands.
2. Highlighting search results would be a very helpful addition as well.  This was also mentioned in #458.

Thank you for considering our ideas :)  Vim-Mode is by far my favourite package.  Thanks for all your hard work on it!

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
