### ISSUE TITLE
support multi-cursor-plus

### ISSUE THREAD

**Issue by wolftune** [atom/vim-mode#855]
https://atom.io/packages/multi-cursor-plus is much more powerful, it seems, vs the plain multi-cursor package. But it doesn't work with vim-mode stuff specifically (it doesn't actually add any keybindings at all, only offers some suggestions). I don't know which side of the equation should add the support, but I opened a ticket there too https://github.com/kankaristo/atom-multi-cursor-plus/issues/3

**Comment by jacekkopecky** [comment]
do you have anything specific in mind that doesn't work with multi-cursor-plus? I could imagine integration like this: motions like `w` could move only the last cursor while the other cursors stay put - is that what you had in mind? That could be cool, and shouldn't be terribly hard.

Of course any vim-mode commands that don't work properly with multiple cursors should be reported.

**Comment by wolftune** [comment]
@jacekkopecky yes, the issues are: (A) nobody has set up keybindings for multi-cursor-plus to work with vim-mode, so someone should do that and share them and (B) the ability to do vim movement commands of all sorts for the last cursor separately would indeed be very cool.

That's it. Otherwise, multi-cursor-plus seems awesome, the best of its ilk.

**Comment by jacekkopecky** [comment]
My preference is for multi-cursor (not -plus) because the alt-x is an extra keystroke I find unnecessary. 

In fact, the demo at multi-cursor-plus, where xe (she or he) puts the cursors after those apostrophes, has much too much cursor movement, from a vim perspective. With vim-mode, as is, do this: 

![atom](https://cloud.githubusercontent.com/assets/807315/9592977/19684ae8-5041-11e5-9501-b724e69530f4.gif)

 1. duplicate the cursor across all those lines (Atom's editor:add-selection-below) no matter what column you're in, 
 2. then go `0f:;` to get the cursors all where you want them; 
 3. then `imulti-cursor-plus<escape>` to add that text; (autocomplete should work the same)
 4. then `B` to get back to the space, then `i<20 spaces><escape` to get all the text past the longest first parth, (this diverges from how xe does it),
 5. `0<24 l>` to get all the cursors in a column where we want the second block to end up,
 6. `dw` to delete the unnecessary spaces.

See, maybe we don't so badly need to have vim-mode motions for *the last cursor* when they normally affect all the cursors and usually, like in this case, that's quite exactly what's needed.

**Comment by wolftune** [comment]
@jacekkopecky Clearly, vim-mode on its own with the built-in Atom multi-cursor functions is already powerful. Nothing more is *needed*. However, there can be cases where the lines you want to edit aren't anything like this example. What if there were interim lines between each of these? Then we'd not be able to do it. Or if the lines were not all the same sort of phrasing.

For Vim itself, there's https://github.com/terryma/vim-multiple-cursors which is nice. It's effectively the same as doing find and substitution type commands but is another approach that's more visual and allows picking out the items one by one. Another approach would be to take an action, then search, then repeat. So, vim-multiple-cursors isn't *needed* but it's neat.

I think multi-cursor-plus support would be *nice* but should not be considered a priority at all. It isn't a matter of getting normal Vim operations working, it's an extra.

**Comment by wolftune** [comment]
One more thought: whether it's connected to this other package or not, what I'm really suggesting is a way to use vim-mode and have a function comparable to the ctrl-click that adds a new cursor under the mouse position. In other words, I want to mark a spot for a cursor, use arbitrary vim moves or searches or whatever to get to a new location (while the old cursor stays) and hit some new-cursor command to then add a cursor there. etc. Which is basically like the ability to add a cursor and then move only the new cursor.

That might just be a new way to explain what I was saying before, or to describe what this is about. I.e. a vim-mode way of working with multi-cursor-plus functionality.

**Comment by jacekkopecky** [comment]
@wolftune sorry if I came across as meaning that *multi-cursor-plus* isn't *needed*, not at all. The pointer to *vim-multiple-cursors* above is also much appreciated, and it shows me how much I've fallen behind modern text editing by sticking to my comfortable old VIM without extensions for so long.

I'm delighted how much of what used to be done with block selections and `q` macros can be done with multiple cursors in a more natural way. (Again, not to say that we no longer need macros and block selections.)

Adding support in vim-mode to easily add multiple cursors is desirable, and this is a valuable issue. Please ping me if it's still open in April.

**Comment by erf** [comment]
I'm using this now with `multi-cursor` - all i need !
```
'.platform-darwin atom-text-editor:not(mini)':
  'ctrl-j': 'multi-cursor:expandDown'
  'ctrl-k': 'multi-cursor:expandUp'
```

**Comment by sjcalamia** [comment]
@jacekkopecky ping. Looks like it's still open.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
