### ISSUE TITLE
Enabling vim mode on Windows disables CTRL+C

### ISSUE THREAD

**Issue by Zeneixe** [atom/vim-mode#857]
It's very annoying, it doesn't happen on Mac because copy/paste use the CMD key... Is it possible to circumvent this problem without remapping any keys?

**Comment by jacekkopecky** [comment]
Yes, this is a conflict; more VIM/windows users could chime in on which key
binding they prefer.

For now, you can restore the desired mapping in your personal keymap by
adding the default one there.

**Comment by mertzt89** [comment]
For what its worth, if you use GVim on windows, the Ctrl-C binding is configured to return to normal mode. So the binding that vim-mode uses reflects the same behavior. I use Ctrl+Insert for the copy operation.

**Comment by robrez** [comment]
On windows, I usually configure a vimrc file to get gvim to play nice.

The rules on windows seem a bit odd... instead of `.vimrc` gvim looks for a `_vimrc`. I suppose its `%HOMEPATH%` (or something wierd like that) instead of `~` or `$HOME`.

Would be cool vim-mode could read the same _vimrc file as gvim. Is a vimrc file currently supported?

**Comment by jvtrudel** [comment]
Same bug for me... Is it planned to fix this by setting the default ctrl-c to !native for windows?

Also, I am quite new (and enthousiat!) as atom user and I do not fully master (yet) the keymap synthax and possibilities. I tried:
```
 '.workspace .editor:not(.mini)':
    'ctrl-c' :'native!'
```

But it doesn't work. What should I do? thx

**Comment by jvtrudel** [comment]
I also tried to restore the core's default:

```
 'body':
   'ctrl-c':'core:copy'

 'body .native-key-bindings':
    'ctrl-c' :'native!'
```

but it doesn't work either...

**Comment by AmethystCat** [comment]
Here may be the solution for you [#541](https://github.com/atom/vim-mode/issues/541).

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
