### ISSUE TITLE
Input VIT, complex HTML, the choice is not correct

### ISSUE THREAD

**Issue by doneself** [atom/vim-mode#858]
Input VIT, complex HTML, the choice is not correct

**Comment by MarkusSN** [comment]
Duplicate of #835?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
