### ISSUE TITLE
Retrace your movements in file not working (keyboard shortcut conflict)

### ISSUE THREAD

**Issue by Dowwie** [atom/vim-mode#861]
Control-O and Control-I shortcuts in vim allow a user to retrace cursor positions

Atom's shortcuts are overriding those for vim

**Comment by jacekkopecky** [comment]
try the `cursor-history` package, it seems to cover these

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
