### ISSUE TITLE
Turn on visual mode when selecting with mouse (regardless of previous mode)

### ISSUE THREAD

**Issue by skosch** [atom/vim-mode#867]
This is related to #295.

When selecting something with the mouse, vim switches to visual mode, regardless of whether one was previously inserting or not. I believe vim-mode should follow this behaviour or at least offer an option to enable this.

I occasionally select passages with my mouse, hit `x` or `d` to cut and then `p` to paste that text somewhere else. However, if I was previously in insert mode, the passage will simply be replaced with "x", the paste fails, and I have to work my way back up vim-mode's precarious undo stack. It's frustrating to lose work this way, and it's happened to me multiple times since installing Atom a few hours ago. Since visual-mode selections and atom-native selections look identical, there is no way of telling which mode you came from.

I understand that there's a worry that this will lead to conflicts with other packages, but I think it would be a valuable option to have at least.

In the meantime, I'd love to patch this on my own machine if someone was willing to help me figure out how to do it (I've mucked around with line 660 in vim-state.coffee, but haven't achieved anything robust)—I'd be very, very grateful!

**Comment by jacekkopecky** [comment]
Hi, line 660 is the right one, did you add `or @mode is 'insert'` ?

Also related to #840.

**Comment by skosch** [comment]
That is what I tried. You can select with the mouse, and when the selection changes (i.e. on mouseup), vim-mode switches to visual mode, but it loses the selection immediately. The code would have express `if @mode is insert then store the atom-selection, switch to visual, then create an equivalent vim-mode-selection`.

**Comment by skosch** [comment]
(Also, I don't feel as strongly about #840 as I do about this one, but I don't see why there couldn't be one option to enable both behaviours. In vim, selection == visual mode, so when I see any selected text in atom, I instinctively assume I can manipulate it with vim commands. I'm sure there are others who feel the same?)

**Comment by maxbrunsfeld** [comment]
I don't think this should be the default, because an important goal of `vim-mode` currently is that it feels like normal Atom when in insert mode. I think it would be great to have an option to enable this behavior though @skosch. I'd be glad to give feedback on and merge a PR adding such an option.

**Comment by skosch** [comment]
Doing this properly is trickier than I thought (and Coffeescript isn't helping the matter ;-).

I'd be very grateful if someone could give me some pointers how to tweak `activateVisualMode` so that it recovers the existing selection! :)

**Comment by vansoest** [comment]
What's about this topic? @skosch have you find an acceptable workaround? ☺️

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
