### ISSUE TITLE
"ciw" doesn't respect delimiters when cursor is at beginning of word

### ISSUE THREAD

**Issue by skosch** [atom/vim-mode#868]
Steps to reproduce (`|` is cursor in normal mode):

`abc.de|f` → type `ciw` → `abc.|` (expected behaviour)
`abc.|def` → type `ciw` → `abc|` (expected: `abc.|`)

Is this an isolated bug or a side effect of a larger existing issue?

**Comment by azoerb** [comment]
+1 this seems to be a newly added bug.

**Comment by tony612** [comment]
+1

**Comment by hdemon** [comment]
+1

**Comment by tony612** [comment]
@maxbrunsfeld I found another bug for the latest version:

`ab|c.def` → type ciw → `.def` (expected behaviour)
`abc|.def` → type ciw → `def` (expected: .def)

**Comment by maxbrunsfeld** [comment]
Thanks for the report, @tony612.

/cc @benmccormick, in case you're interested in looking into that one as well, despite how long it took me to merge your last PR. :bow:

**Comment by benmccormick** [comment]
Yeah I'll take a look.  Probably should have realized that would be a problem the first time.  For some reason I seem to delete/change from the start of words much more often than the end.

**Comment by benmccormick** [comment]
@maxbrunsfeld so as far as I can tell the root issue here is really this: https://github.com/atom/atom/issues/6538  It seems like getCurrentWordBufferRange has issues.  As far as I can tell its behavior is greedy to the right

1. If the cursor is just selecting part of a word or has no selection but is inside a word, it just selects that word (this is why the ciw behavior used to work a good deal of the time)

2. If the cursor/selection is adjacent to 2 "words" and there is no selection, it grabs both words. This is what was causing the original issue I fixed.  Unfortunately I thought this was because it wasn't able to tell which word to grab if there was no selection.  But in reality it seems that its a bit more complicated.  If its just a plain cursor it grabs both.  But if there is a selection that ends on a word boundary, it grabs the selected word and a word to the right.  

So thats a bug there.  I think working around that probably requires reimplementing at least some of the getCurrentWordBufferRange in vim-mode, or as a hack, calculating the range twice if the selector is empty (which it really always should be for text objects).  We could calculate it once with just the empty cursor, once with a selection of the character to the right of the cursor, and then take the smaller of the 2 selection.

Thats a horrifically hacky workaround to something that should probably be resolved upstream of this repo though.

**Comment by benmccormick** [comment]
@maxbrunsfeld looks like https://github.com/atom/atom/pull/8906 is headed in the right direction for vim-mode to be able to fix this cleanly without hacks, so I'll keep an eye on that and put out a PR here if necessary when that goes through (possibly the result of that PR will just fix this issue?  I'm not totally positive.  It will definitely make it clean to fix)

**Comment by maxbrunsfeld** [comment]
@benmccormick Thanks for figuring that out; sounds exactly right. Let's stay tuned for atom/atom#8906.

**Comment by benmccormick** [comment]
@drifkin you could pull request something?  I didn't see a good way to catch both ends of the bugs without getting much much hackier.  And I don't like doing that to other people's codebases :)  But if you see a better idea I'd be curious.
