### ISSUE TITLE
Docs are out of date

### ISSUE THREAD

**Issue by geo7** [atom/vim-mode#870]
From the overview : 

"There are only currently two modes, normal mode and insert mode"

Apparently there _is_ a visual mode. 

...

**Comment by maxbrunsfeld** [comment]
Yeah, there are probably other things in there that are out-of-date as well. If you're interested in contributing some prose, I'd love to merge a PR fixing up those docs.

**Comment by geo7** [comment]
I was thinking about using Atom because I thought it was *more* complete, not less ;)

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
