### ISSUE TITLE
typing "ge" should jump to end of previous word

### ISSUE THREAD

**Issue by wbolster** [atom/vim-mode#871]
... but instead if behaves just like "e" and jumps to the end of the current word.

**Comment by charlesswartz** [comment]
:+1: I would love to see this

**Comment by developertenzin** [comment]
Yes, same here! I would like this to be solved ASAP. :+1:

**Comment by AmZaf** [comment]
The same bug also applies to the "gE" command. I see commits mentioned here but still no fix in the official package.

**Comment by jdshatz** [comment]
Are there ways to make the command regardless of case?  There are different permutations: gE, ge, Ge, GE.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
