### ISSUE TITLE
Jump-to-nearest when selecting around/inside quotes includes all characters beginning at cursor

### ISSUE THREAD

**Issue by MarkusSN** [atom/vim-mode#872]
Steps to reproduce:
Given a line `var a = 'awesome text'`
Place cursor over `r` and input `vi'`
Expected selection `awesome text`
Actual selection `r a = 'awesome text`

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
