### ISSUE TITLE
Undo/Redo should *never* leave text selected.

### ISSUE THREAD

**Issue by jordwalke** [atom/vim-mode#882]
In fact, it's _really_ bad when it does leave text selected because you cannot continue to undo/redo.

I noticed this within the first ten second of trying this plugin.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
