### ISSUE TITLE
w command doesn't jump from last word of line to next line

### ISSUE THREAD

**Issue by jpanda109** [atom/vim-mode#885]
Using the w command while on the last word of doesn't move the cursor to the first word of the next line as it's supposed to in normal vim.

Atom: 1.0.19
OS: Windows 10
vim-mode: 0.60.0

**Comment by mattr-** [comment]
I can't confirm this with the following:

Atom: 1.0.19
OS: Mac OS X 10.10.5
vim-mode: 0.60.0

Perhaps we're looking at an issue with line-ending style detection?

**Comment by sgronblo** [comment]
I just updated to the latest version (0.61.0) and have the same problem today, I feel like maybe it was working before though. Atom 1.0.19 and OSX 10.10.5.

**Comment by sgronblo** [comment]
Ah actually this was a file that I had created on Windows, so changing the line endings from CRLF to LF made it work.

**Comment by cheniel** [comment]
Issue on atom core: atom/atom#9270

**Comment by rluiten** [comment]
The 1.40 beta fixed the problems I had, this might be addressed to worth checking.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
