### ISSUE TITLE
Exception is thrown when Register Prefix gets called from the command-palette

### ISSUE THREAD

**Issue by andischerer** [atom/vim-mode#887]
see andischerer/atom-keyboard-localization#75

Steps to reproduce:
- Open command palette (ctrl+shift+p)
- type reg and enter(vim-mode:Register Prefix)

**Atom Version**: 1.0.19
**vim-mode**: v0.60.0

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
