### ISSUE TITLE
ctrl + w close tab is  slow 

### ISSUE THREAD

**Issue by easthing** [atom/vim-mode#905]
Use ctrl + w in ubuntu system is very slow closing tab

**Comment by maxbrunsfeld** [comment]
Yeah, this is because there are [key bindings](https://github.com/atom/vim-mode/blob/master/keymaps/vim-mode.cson#L159) for sequences like `ctrl-w h` and `ctrl-l` for moving between splits, so Atom is waiting to see if you're going to type an `h`, `l`, etc. I'm not sure what's the right thing to do here, because those bindings are an important part of vim, on all platforms. Do you have any thoughts, @easthing?

**Comment by Samcfuchs** [comment]
Could it be switched to `ctrl-shift-w [h, l]`? Or switch the close tab binding to that?

**Comment by easthing** [comment]
@maxbrunsfeld understood thinks

**Comment by maxbrunsfeld** [comment]
:+1:
