### ISSUE TITLE
Not by typing "w", jump to the next line, has remained at the end of the line

### ISSUE THREAD

**Issue by doneself** [atom/vim-mode#910]
Not by typing "w", jump to the next line, has remained at the end of the line

**Comment by masukomi** [comment]
if "Not by typing 'w'", then how? What *are* you doing that's causing a problem. I can jump to the next line without using w in multiple ways and all the ones I've tried work.

**Comment by cheniel** [comment]
Perhaps it's the same issue as #885?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
