### ISSUE TITLE
dk deletes one line when the cursor is at the beginning of the line

### ISSUE THREAD

**Issue by jazzpi** [atom/vim-mode#913]
In this file (cursor is on the g):

```
abc
def
ghi
```

pressing `dk` will only delete the second line, but not the third. If the cursor is on the h, it behaves correctly.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
