### ISSUE TITLE
cw on whitespace replaces the next word instead of the whitespace (vim-parity)

### ISSUE THREAD

**Issue by globau** [atom/vim-mode#916]
given:

```
hello world test
     ^
```

with the cursor over the space between the words and pressing 'cw' (change word), vim-mode behaves differently from vim.

vim:

```
helloworld test
     ^
```

vim-mode:

```
hello test
     ^
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
