### ISSUE TITLE
Visual mode doesn't work at end of file

### ISSUE THREAD

**Issue by bronson** [atom/vim-mode#921]
To reproduce:

Type `G` to go to the end of the file, then `v` or `V` to start a visual selection.

Expected: the selection starts.

Actual: the `v` is ignored.

Workaround: hit `kv`.  Everything works fine if you start the visual selection on the second-to-last line.

**Comment by bronson** [comment]
Atom allows you to put the cursor after the last newline in the file and Vim doesn't.  So, maybe the correct fix is to have normal mode disallow moving the cursor below the last line in the file?  Not sure.

I notice non-vim-mode Atom doesn't allow triple-clicking the last line in the file either.  It has no trouble at all triple-clicking blank lines everywhere else.  Maybe this issue isn't restricted to vim-mode?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
