### ISSUE TITLE
<esc> a should append, but does the same as <esc> i (insert)

### ISSUE THREAD

**Issue by misterdavemeister** [atom/vim-mode#928]
I just encountered an issue where having the cursor at the end of the line and using esc-a would not append to the end of the line, but instead INSERT (esc-i) in front of the last character in the line, which made it so that I couldn't type beyond the last character. 

looking at the keymap, it looks like esc-a is given the exact same functionality as esc-i which is not like vim at all. It would be incredibly awesome if this could be fixed!

**Comment by falm** [comment]
Same error at 0.65.1

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
