### ISSUE TITLE
Substitute command cannot insert new lines

### ISSUE THREAD

**Issue by sneuberger** [atom/vim-mode#932]
1. Make a new file with contents `hello`
2. Type `:s/l/l\r/g` and press Enter

Expected: File should become:

```
hel
l
o
```

Actual: File becomes `helrlro`

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
