### ISSUE TITLE
open how do you launch the thing? your docs say nothing about it 

### ISSUE THREAD

**Issue by stavinopolis** [atom/vim-mode#933]

**Comment by mwleeds** [comment]
vim-mode should launch automatically in normal mode once the package is installed.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
