### ISSUE TITLE
G goes to end of last line

### ISSUE THREAD

**Issue by dubiousdavid** [atom/vim-mode#934]
`G` should go to the beginning of the last line and not the end of the last line. That is the behavior in VIM.

**Comment by mysyljr** [comment]
Me too

**Comment by bronson** [comment]
Actually, Vim tries to leave the cursor in the same column it started in.

**Comment by bronson** [comment]
Damn it, Vim is inconsistent.  This behavior depends on the `startofline` setting.

http://stackoverflow.com/questions/8292742/vim-cursor-jumps-to-begining-of-the-line-after-buffer-switch

Everyone sets `nocompatible`, right?  If so, then it seems like most people would expect `nostartofline`...  But I guess this is open to discussion.

**Comment by t9md** [comment]
@bronson as my understanding this issue is report for the behavior 'cursor past last newline'.

If this is for about startofline option behavior, cursor position report is whether start of line OR firstchar of line.

**Comment by bronson** [comment]
Drat, you're right.  Hope vim-mode receives that fix.  :)

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
