### ISSUE TITLE
Selecting a block with "V$%" doesn't work

### ISSUE THREAD

**Issue by rdbell** [atom/vim-mode#936]
``` c
function run() {
    func_one();
    func_two();
}
```

Start with cursor at the top line. In Vim, V$% will select the entire function including opening and closing braces. In atom vim-mode V$% will only select the top line.

**Comment by rdbell** [comment]
Atom: 1.3.1

OS X: 10.11.1 (15B42)

vim-mode: 0.63.0

**Comment by vignesh-m** [comment]
v$ stops at last character in vim, but extends to whole line in vim-mode.
Was this supposed to be fixed in [#2](https://github.com/atom/vim-mode/issues/2) ?

**Comment by bronson** [comment]
It's a different issue.  #2 prevented the cursor from moving past the last character in the line.  This issue is because linewise visual mode currently locks the cursor to whatever column it started on.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
