### ISSUE TITLE
"dT" sometimes deletes the character infront of the cursor

### ISSUE THREAD

**Issue by rdbell** [atom/vim-mode#937]
``` c
if (!something()) {
}
```

Place cursor between 'n' and 'g'. 

'dT!' gives the output:

``` c
if (!()) {
}
```

Output should be:

``` c
if (!g()) {
}
```

Similar commands such as 'db' behave properly in the same situation.

**Comment by rdbell** [comment]
Atom: 1.3.1

OS X: 10.11.1 (15B42)

vim-mode: 0.63.0

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
