### ISSUE TITLE
Scroll window up/down fails sporadically

### ISSUE THREAD

**Issue by dcalhoun** [atom/vim-mode#941]
The scroll window [up](http://vimhelp.appspot.com/scroll.txt.html#CTRL-Y)/[down](http://vimhelp.appspot.com/scroll.txt.html#CTRL-E) commands no longer work consistently.

### Behavior
As a user, I press and hold <kbd>ctrl</kbd> + <kbd>e</kbd> or <kbd>ctrl</kbd> + <kbd>y</kbd>.

### Expected Outcome
They editor moves up or down by a single (1) line for as long as I hold the keys, until reaching the end of the document.

### Current Outcome
The editor:
- Moves a single line, then halts.
- Does nothing for a few seconds, then begins scrolling as expected.
- Scrolls the document, but displays artifacts frozen in place.

### Environment
- Mac OS X 10.11.2 (15C50)
- Atom v1.3.2
- vim-mode v0.64.0
- Various different files types (e.g. – `.html.erb`, `.scss`, `.js`)

cc/ @maxbrunsfeld – possibly related to your changes in #938. This seemed to start with v0.64.0.

**Comment by gittyupagain** [comment]
Scrolling feedback is only shown in the main window when the cursor is on the 3rd or 4th line from the top (with <kbd>ctrl</kbd> + <kbd>e</kbd>) or bottom (with <kbd>ctrl</kbd> + <kbd>y</kbd>). When the problem is happening, the proper view isn't updated until another key is pressed, or the cursor reaches the 3rd or 4th line. The minimap window properly shows what _should_ be shown in the main window, regardless of cursor position.

**Comment by dcalhoun** [comment]
This bug appears to affect **all scroll commands** (e.g. – [half page down](http://vimhelp.appspot.com/scroll.txt.html#CTRL-D), [page down](http://vimhelp.appspot.com/scroll.txt.html#CTRL-F)).

If you use <kbd>ctrl</kbd> + <kbd>f</kbd> to scroll to the bottom of the document, you end up a few lines (~10) above the bottom with the cursor off the screen. After reaching the bottom of the document, if you press <kbd>k</kbd>, the window jumps to reveal the bottom of the document and the cursor.

**Comment by maxbrunsfeld** [comment]
@dcalhoun @gittyupagain Sorry for the poor experience continuing. I can't reproduce this on my master build of Atom, I'm wondering if it was fixed by either https://github.com/atom/atom/pull/9444 or https://github.com/atom/atom/pull/10062.

If you're interested, could you try Atom v1.4.0-beta3? The first PR mentioned above is included in that release. If that doesn't help, I believe the fix may be on master, and we're going to release *new* beta and stable versions by Wednesday.

**Comment by gittyupagain** [comment]
I just tried Atom v1.4.0-beta3, and I still see the <kbd>ctrl</kbd>+<kbd>e</kbd> / <kbd>ctrl</kbd>+<kbd>y</kbd> problem. I don't see the problem with <kbd>ctrl</kbd>+<kbd>f</kbd> that @dcalhoun is seeing, but I didn't see that with Atom v1.3.3 either.

Trying to isolate the problem, I removed my ~/.atom directory. After relaunching and installing just vim-mode, I still see the problem with Atom v1.4.0-beta3.

**Comment by dcalhoun** [comment]
I never tried Atom v1.4.0-beta, but this bug is definitely still a problem in the v1.4.0 release.

**Comment by dragonxlwang** [comment]
yes, it is still a bug in v1.4.1. Hope it could get fixed soon.

**Comment by narychen** [comment]
+1

**Comment by dcalhoun** [comment]
Both issues appear to be resolved in Atom v1.4.2.

**Comment by maxbrunsfeld** [comment]
Really sorry for the wait on this one @dcalhoun. I thought I had back-ported the fix to an earlier release :grimacing:.
