### ISSUE TITLE
Ctrl+V -> Shift+G not working properly

### ISSUE THREAD

**Issue by Qix-** [atom/vim-mode#943]
Entering block selection and then jumping to the end of the document (`Ctrl+V, Shift+G`) enters visual block mode and then switches to visual mode when you hit `Shift+G`. It should just select the current column width down to the bottom-most applicable line.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
