### ISSUE TITLE
Visual mode doesn't go to the opposite direction if start from blank line

### ISSUE THREAD

**Issue by ryandao** [atom/vim-mode#945]
I found a rather strange issue when starting visual mode from a blank line. If I move the cursor up and then down pass the starting line, visual mode goes away. Here's an example:

![vim-mode-issue](https://cloud.githubusercontent.com/assets/705116/12141079/8d29f844-b4a7-11e5-9ab6-ef4bc508f746.gif)

Here's the expected behavior in Vim, which keeps the visual mode when the cursor goes in opposite direction.

![vim-mode-issue-1](https://cloud.githubusercontent.com/assets/705116/12141101/ae0aae6e-b4a7-11e5-8649-7ee79af25da1.gif)

**Comment by angel1a** [comment]
I am wondering which software should I use to record my action like this so that I can report my bug conveniently as well.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
