### ISSUE TITLE
Add set syntax command

### ISSUE THREAD

**Issue by smaili** [atom/vim-mode#949]
Opening a feature request issue for the `:set syntax` command that we all know and love :)

So for example, typing the following:

``` vim
:set syntax=html
```

would automatically set the current file's syntax highlight to html.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
