### ISSUE TITLE
visual confirmation with yy

### ISSUE THREAD

**Issue by jsolack** [atom/vim-mode#951]
Would it be possible to add visual confirmation with commands like yy?  vim-mode-plus and vintageous (for sublime) both do this and i find it helpful with copying a block of text such as 28yy to see some visual queue of what was yanked.

**Comment by jacekkopecky** [comment]
Hi, out of curiosity, why do you prefer to use vim-mode over vim-mode-plus? (I haven't tried vim-mode-plus myself, but I hope to try it one day.)

**Comment by jsolack** [comment]
One big reason is it doesn't support ex-mode, I can't use :w to write a file...

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
