### ISSUE TITLE
Can't search for a literal backslash followed by c

### ISSUE THREAD

**Issue by graue** [atom/vim-mode#957]
**Reproduction steps**
1. Put this in a file: `encode \code`
2. Move cursor back to the beginning
3. Press / and enter the search `\\code`

**Expected behavior**

Since I escaped the backslash, this should be treated as me searching for `\code` and should jump to that.

**Observed behavior**

Acts like a search for "ode", so jumps to midway through the word "encode".

Seems to be caused by #366

**Comment by tangledhelix** [comment]
This `\c` magic  escape seems confusing and unexpected, especially since it is not emulating something that is in either Vim or Atom's native search.

I don't have time at present to write/test a PR for it, but seems to me that a better approach might be to emulate the way that Vim handles the case-sensitivity problem, by appending `/i` at the end of the pattern. That does not interfere with `\` escapes or searching for strings containing `\` as in this issue, and you can include a literal `/` in your search with a simple escape, `\/`.

(I will try to write/test a PR for this in the next couple of days, time permitting...)

**Comment by tangledhelix** [comment]
I am not sure this should be labeled a bug. This is emulating Vim's behavior (which is, after all, the point of vim-mode, I assume?)

See the below quote, from `:help /\c`. One could contend that this should be left as-is, and extended to include the `\C` escape as well (if it isn't already there).

```
                                                        */\c* */\C*
When "\c" appears anywhere in the pattern, the whole pattern is handled like
'ignorecase' is on.  The actual value of 'ignorecase' and 'smartcase' is
ignored.  "\C" does the opposite: Force matching case for the whole pattern.
{only Vim supports \c and \C}
Note that 'ignorecase', "\c" and "\C" are not used for the character classes.

Examples:
      pattern   'ignorecase'  'smartcase'       matches ~
        foo       off           -               foo
        foo       on            -               foo Foo FOO
        Foo       on            off             foo Foo FOO
        Foo       on            on                  Foo
        \cfoo     -             -               foo Foo FOO
        foo\C     -             -               foo
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
