### ISSUE TITLE
Auto disable IME in normal mode?

### ISSUE THREAD

**Issue by hh9527** [atom/vim-mode#962]
VIM already support this feature for many years.

When switch to normal mode from insert/replace mode via `ESC`, the IME should be disabled automatically, and re-enable IME when go back to inser/replace mode.

Is it possible to support this feature in atom/vim-mode? It is very important feature for writing documents in non-western languages.

**Comment by oldratlee** [comment]
:+1:  like and need this feature badly :smile:

**Comment by yubaoquan** [comment]
Same need. Is atom team still maintaining this package?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
