### ISSUE TITLE
emoji support in visual mode

### ISSUE THREAD

**Issue by JonathanMH** [atom/vim-mode#963]
When the cursor is on an emoji in visual mode, it selects more than that character.
Screenshot:
http://imgur.com/OxcyXIU

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
