### ISSUE TITLE
Deletes special character if cursor is next to one with ciw

### ISSUE THREAD

**Issue by kyleholzinger** [atom/vim-mode#969]
Sorry if this is a duplicate issue, I tried searching for it and couldn't find anything. This issue has to do with the command `ciw` in normal mode, aka change in word. If your cursor is next to a special character, such as `(`, `"`, or `?` (for example), doing `ciw` before that character will also delete said special character, which it should not. Ex:

doing `ciw` in the following string, when your cursor is on the `t`

``` ruby
some_object.present?
```

results in the following

``` ruby
some_object.
```

however, it should result in

``` ruby
some_object.?
```

with the cursor between the `.` and the `?`

**Comment by wmassa** [comment]
This is because of an issue in Atom: https://github.com/atom/atom/issues/9851

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
