### ISSUE TITLE
Use clipboard as default register setting reset itself

### ISSUE THREAD

**Issue by artoale** [atom/vim-mode#971]
I believe this might be because of the default value of true added by #940 (not sure, tbh).

The problem I encounter is that quite often, I suspect when I open a new Atom window, the settings goes back to `true`, even if I untick the config. I even tried to put the value hardcoded to `false` in the config file, but no luck, it gets reset after a while.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
