### ISSUE TITLE
mouse paste at cursor position

### ISSUE THREAD

**Issue by abate** [atom/vim-mode#972]
Hi, I've already asked this question on the Atom forum (https://github.com/atom/atom/issues/10971), and I'm wondering if this is a behavior (or configuration option) that vim-mode would like to take on board. The idea is that when you copy paste with the middle button, the text is pasted at cursor position instead of the position of the mouse cursor. When using vim, this a pretty common action. I paste something, I go back to the editor, then forgetting about the mouse position I click the middle button. This how to do it, but since I'm not really familiar with the atom code, this is also not entirely clear to me ...

> This isn't something you can really configure right now and not a sufficiently popular request
> to take the time to make it configurable. If you'd like to modify the behavior in your own copy 
> of Atom, you could override TextEditorComponent.prototype.onMouseDown and opt out of 
> changing the selection when the event's button property is 1.

**Comment by agrossfield** [comment]
I too would like to see this behavior.  As I convert from vim, I constantly make this mistake, and I'd love to be able to paste at the insert cursor.

**Comment by GitJer** [comment]
As do I!

**Comment by lqueryvg** [comment]
This is not just a vim thing.

Paste should **always** paste at the insert cursor position, not the mouse position.
I'm struggling to think of a single application or text entry field where paste does *not* behave in this way.
The text entry box I'm using to post this message on Github is just one of many many examples.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
