### ISSUE TITLE
XML tag text object functionality

### ISSUE THREAD

**Issue by sandman21dan** [atom/vim-mode#973]
Couldn't find this a similar issue already opened, What I'm talking about is Vim's XML tag recognition.

Specifically, `<span>My Text</span>` and anywhere inside these tags I could hit cit (change inner tag) and I would end up with `<span>|</span>` with the pipe meaning the cursor located inside the tags in insert mode.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
