### ISSUE TITLE
Explicit indent ranges are broken

### ISSUE THREAD

**Issue by knownasilya** [atom/vim-mode#974]
So the following works: `<<` and `<3<`.

But this produces an error: `:15,35<` as well as `:15,.<`. Other commands like `:15,35d` work.

> Command error: Not an editor command: 15,35<

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
