### ISSUE TITLE
:<linenumber> goes to (current line number + <linenumber>)th line

### ISSUE THREAD

**Issue by koorgoo** [atom/vim-mode#975]
Current line number is 10. Type `:5<Enter>`. Now current line number is 15 (10+5).
vim-mode 0.64.0
Atom 1.5.4
Mac OS X 10.11.3

**Comment by tangledhelix** [comment]
This is not reliant on the `:` being typed. `5`<kbd>Enter</kbd> behaves exactly the same way.

**Comment by koorgoo** [comment]
`:5<Enter>` must set the current line to the 5th one just like Vim does it.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
