### ISSUE TITLE
Implement za (toggle fold)

### ISSUE THREAD

**Issue by morenoh149** [atom/vim-mode#977]
From http://vim.wikia.com/wiki/Folding

I see `z c` and `z o` already are working https://github.com/atom/vim-mode/blob/72214e5e67233cc0a55817b8a38db3177a5e7a81/keymaps/vim-mode.cson#L130 how can we conditionally execute one method based off the fold status?

**Comment by aminroosta** [comment]
My solution:

`init.coffee`

```
atom.commands.add 'atom-text-editor',
  'editor:toggle-folding': (event) ->
    editor = @getModel()
    bufferRow = editor.bufferPositionForScreenPosition(editor.getCursorScreenPosition()).row
    if editor.isFoldedAtBufferRow(bufferRow)
      editor.unfoldBufferRow(bufferRow)
    else
      editor.foldBufferRow(bufferRow)
```

& in `keymap.cson`
```
'atom-text-editor.vim-mode:not(.insert-mode)':
  'z a': 'editor:toggle-folding'
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
