### ISSUE TITLE
Change inner ignores last command

### ISSUE THREAD

**Issue by Silur** [atom/vim-mode#978]
I can use `ciw` (change inner word) but cannot use `ci'` for eg in JS files or `ci/` with regexes because the plugin is ignoring the characters and waits at `ci` for the last command.

**Comment by mauskin** [comment]
As of Atom 1.9.9 and vim-mode 0.65.1 `ci'` works fine for me and `ci/` doesn't.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
