### ISSUE TITLE
Bracket matching with HTML tags

### ISSUE THREAD

**Issue by colbycheeze** [atom/vim-mode#979]
Hi, currently the vim matching with `%` works great for everything except HTML/XML tags.

I can change my % macro to use the bracket-matcher command of:
`'%': 'bracket-matcher:go-to-matching-bracket'`

buuut...that doesn't allow me to do vim commands of selecting, deleting, changing etc etc.

Any plans to add this?

**Comment by trusktr** [comment]
Much needed!

**Comment by johndangerstorey** [comment]
Yeah, we need html tag matching pretty please with sugar on top?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
