### ISSUE TITLE
replace with confirmation?

### ISSUE THREAD

**Issue by dragonxlwang** [atom/vim-mode#981]
Hi, Is it supposed that replace with confirmation is not working currently?
![untitled](https://cloud.githubusercontent.com/assets/15812510/13717032/6b048ac4-e7a4-11e5-9e47-5c93c107da33.gif)

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
