### ISSUE TITLE
`gn` command does not work like in Vim

### ISSUE THREAD

**Issue by greduan** [atom/vim-mode#983]
Let's assume the following text:

```
|foo
bar
foo
fez
```

`|` is the cursor, of course it's in block mode so in that case it's actually on the `f` character.

In Vim, if I search for `foo` with `/`, and then do `cgnFOO<esc>` the text would be:

```
FO|O
bar
foo
fez
```

And then `.` would result in:

```
FO|O
fez
```

Instead in Atom doing `cgnFOO<esc>` results in:

```
FO|Ofoo
fez
```

This I imagine is caused because `gn` is treated like a motion and not as a text-object.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
