### ISSUE TITLE
Regression: Navigate to end of line includes end of line character

### ISSUE THREAD

**Issue by EntilZha** [atom/vim-mode#984]
I was surprised to find this happening:

Code example:

``` python
def testing(asdf, qwer):
    a =  asdf + qwer
    return a
```

With the cursor on `asdf`, typing `v$s` should go into visual mode, select to end of line, then substitute. In regular vim, it correctly does not wipe out the end of line character. In Atom `vim-mode` it does. Could a recent change have caused this or something wrong with my Atom `vim-mode`? Would be happy to do further testing if others can't reproduce

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
