### ISSUE TITLE
Request: Escape key closes panels when already in normal mode

### ISSUE THREAD

**Issue by calebmeyer** [atom/vim-mode#985]
In sublime, if you are find and replacing, and you hit Escape (or your key for return to normal mode), it returns to normal mode the first time you hit it. Then it closes any panels that aren't the tree-view or in a tab.

I'd like for atom to repeat the behavior. 

Things I'd expect to close on the second ESC:
Find and Replace
Find and Replace in project
File finder
Command palette
Error popups
[Git timemachine](https://atom.io/packages/git-time-machine)
Anything else at the bottom of the window (that doesn't have its own tab)

Things I'd expect to remain open on the second ESC:
The tree view
Anything with a tab. This includes:
- Editors
- Markdown Preview
- [Rspec runner window](https://atom.io/packages/rspec)
- Settings window

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
