### ISSUE TITLE
Text deletion behavior (delete or backspace key) does not repeat by dot command.

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [atom/vim-mode#986]
suppose that I want to delete '+' character on the end of line.

```
<html>+
  <body>+
  </body>+
</html>+
```

In native(real vim editor) vim,
delete first line using `A` `backspace` `<ctrl>-C`,
and after that, I can delete just `j` `.` using `dot` repeat command.

vim-mode does repeat well for inserting something,
but it doesn't repeat for deleting something.

I tested in below env:
env1:
  Ubuntu 14.04, atom 1.6.0, vim-mode 0.65.0
env2:
  windows 7, atom 1.6.0, vim-mode 0.65.0

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
