### ISSUE TITLE
how to force case sensitive search with smartcase on

### ISSUE THREAD

**Issue by dragonxlwang** [atom/vim-mode#987]
it is great to have smartcase in vim-mode. But my question is a few times I might want to force case-sensitive search. In vim, I could do it by `/\C{pattern}`, but it seems that `\C` flag is not recognized by atom yet. (Please correct me if I am wrong).

Is there a good way to occasionally toggle case sensitivity in vim-mode?

Thanks,

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
