### ISSUE TITLE
Opening the Settings with a file focused in Normal mode

### ISSUE THREAD

**Issue by Industrial** [atom/vim-mode#990]
Hi.

When I press CTRL-, in normal mode in a file, the combo isn't picked up. When I take the mouse and click in the file tree and then press CTRL-, then it does work.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
