### ISSUE TITLE
Completely not working

### ISSUE THREAD

**Issue by albertorestifo** [atom/vim-mode#992]
I'm using Atom 1.6.1 on OSX 10.11.4

I installed `vim-mode` and it's simply not working. I'm presented with a square cursor. I can only move around the cursor with the arrow keys.

VIM "arrow" keys do not respond and pressing i or v does not seem to enter insert nor visual mode. No keypress seems to be registered.

I attempted disabling all other installed packages and restarting multiple times. There does not seem to be any related error printed in the console.

Any idea what I can try?

**Comment by zcstarr** [comment]
I'm getting the same issue with 1.6.2 any thoughts ?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
