### ISSUE TITLE
ctrl-d in insert mode ... weird behavior

### ISSUE THREAD

**Issue by the-michael-toy** [atom/vim-mode#993]
```
left
    mid
right
```

move to `mid` and hit "o" (open new line after) and then CTRL-D

on vim, the cursor moves to the left column of the blank line, with the `^` representing the cursor ...

```
left
    mid
^
right
```

in vim-mode it looks like this

```
left
    mid
    ^right
```

Which I suppose means ctrl-d is being treated as "delete" and not "inverse indent".

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
