### ISSUE TITLE
Surroundings(ds, das, etc.) don't seem to work

### ISSUE THREAD

**Issue by nabsiddiqui** [atom/vim-mode#994]
In Vim, when you type in ds in "vim/normal" mode, you can delete surroundings by typing in ds.  It seems to not work in vim-mode.

**Comment by chriscasola** [comment]
@nabsiddiqui I think you need the surround plugin for vim to get that behavior. There is another atom package that seems to add surround support: https://atom.io/packages/vim-surround

**Comment by nabsiddiqui** [comment]
Thanks for the help.  I didn't know that package existed.  It only does some of the things that vim does though.  For instance, in a Markdown document heavy with prose, typing in 'das' would usually delete the current sentence.  The vim-surround package, on the other hand, seems to only delete a couple of markers surrounding quotes, parenthesis, etc.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
