### ISSUE TITLE
Shift-A requires a reset of package

### ISSUE THREAD

**Issue by ilyakatz** [atom/vim-mode#995]
`Shift-A` doesn't put the cursor at the end of the sentence but one character before the end. It woks fine when I disable/reenable vim-mode extension 

Here is an illustration

http://take.ms/WvZzf

**Comment by amfarrell** [comment]
This is also the case with 'a' when the cusor is over the last character. The fix of disabling/reenabling also applies.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
