### ISSUE TITLE
changes are shown when file opens

### ISSUE THREAD

**Issue by tylerthehaas** [atom/vim-mode#996]
Anytime I open a file it shows that changes have been made even before typing.  This happens whther I open it through the fuzzy finder or through the file tree.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
