### ISSUE TITLE
Failing unit tests in master

### ISSUE THREAD

**Issue by chriscasola** [atom/vim-mode#998]
I think the unit tests are failing due to a change in the `editor.moveToBeginningOfNextParagraph()` in atom.

I opened atom/atom#11354 to fix the behavior.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
