### ISSUE TITLE
Is there a motion to comment code?

### ISSUE THREAD

**Issue by bookercodes** [atom/vim-mode#999]
Is there a motion to comment code? e.g. `gcap` to comment a paragraph or `gcc` to comment a line. Thanks.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
